document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const ROLES={'Joueur Gamer':['🎮','BONS'],'Loup Gamer':['🐺','HACKERS'],'Healer':['❤️‍🩹','BONS'],'Stratège':['🧠','BONS'],'Support':['🤝','BONS'],'Analyste':['🔎','BONS'],'Speedrunner':['⚡','BONS'],'Hacker':['💻','HACKERS'],'Saboteur':['🧨','HACKERS'],'Manipulateur':['🎭','SOLO'],'Chaos':['🌀','SOLO'],'Opportuniste':['🎯','SOLO'],'Boss Final':['👑','SOLO'],'Traître':['🗡️','BONS']};
let S={peer:null,host:false,room:'',me:'',players:[],roles:[],max:8,game:null,conns:{}};
const go=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active')};
const say=t=>{if($('onlineStatus'))$('onlineStatus').textContent=t};
const send=(c,m)=>{if(c?.open){c.send(m);return true}return false};
const alive=()=>S.players.filter(p=>p.alive);
const pub=()=>S.players.map(p=>({pseudo:p.pseudo,alive:p.alive}));
const hacker=p=>p&&(p.role==='Loup Gamer'||p.role==='Hacker'||p.role==='Saboteur'||(p.role==='Traître'&&S.game?.round>=3));
function navLobby(){go('onlineLobby');$('roomCodeDisplay').textContent=S.room;$('lobbyPlayers').innerHTML=S.players.map((p,i)=>`<div class="player ${i?'':'active'}"><strong>${esc(p.pseudo)}</strong><span>${i?'🟢 Joueur':'👑 Hôte'}</span></div>`).join('');$('startOnlineGameBtn').style.display=S.host?'block':'none';$('lobbyOptionsBtn').style.display=S.host?'block':'none';$('startOnlineGameBtn').disabled=S.players.length<5}
function makePeer(id,cb){if(S.peer)try{S.peer.destroy()}catch(e){}try{S.peer=new Peer(id||undefined,{debug:0})}catch(e){say('❌ PeerJS indisponible.');return}S.peer.on('open',cb);S.peer.on('error',e=>{console.error(e);let m=e.type==='peer-unavailable'?'❌ Salon introuvable.':e.type==='unavailable-id'?'❌ Code déjà utilisé, recrée le salon.':'❌ Connexion impossible : '+e.type;say(m);if(e.type==='peer-unavailable'||e.type==='unavailable-id')alert(m)})}
function create(){let p=$('createPseudo').value.trim();if(!p)return alert('⚠️ Entre ton pseudo.');S={...S,host:true,me:p,players:[{pseudo:p,alive:true,peerId:null,role:null,speed:false}],conns:{},game:null,max:+$('onlinePlayerCount').textContent||8,roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)};say('Création du salon…');let id='LG64-'+Math.random().toString(36).slice(2,8).toUpperCase();makePeer(id,pid=>{S.room=pid;S.peer.on('connection',incoming);navLobby();say('🟢 Salon prêt. Partage le code.');})}
function incoming(c){S.conns[c.peer]=c;c.on('data',m=>hostMsg(c,m));c.on('close',()=>{let p=S.players.find(x=>x.peerId===c.peer);if(p){S.players=S.players.filter(x=>x!==p);delete S.conns[c.peer];broadcast({type:'lobby',players:pub(),max:S.max,roles:S.roles});navLobby()}})}
function broadcast(m){Object.values(S.conns).forEach(c=>send(c,m))}
function hostMsg(c,m){if(!m)return;if(m.type==='join'){let p=String(m.pseudo||'').trim();if(S.game)return send(c,{type:'error',text:'La partie a déjà commencé.'});if(!p)return send(c,{type:'error',text:'Pseudo invalide.'});if(S.players.some(x=>x.pseudo.toLowerCase()===p.toLowerCase()))return send(c,{type:'error',text:'Pseudo déjà utilisé.'});if(S.players.length>=S.max)return send(c,{type:'error',text:'Salon complet.'});S.players.push({pseudo:p,alive:true,peerId:c.peer,role:null,speed:false});S.conns[c.peer]=c;send(c,{type:'joined',room:S.room,players:pub(),max:S.max,roles:S.roles});broadcast({type:'lobby',players:pub(),max:S.max,roles:S.roles});navLobby();return}let p=S.players.find(x=>x.peerId===c.peer);if(m.type==='ready')ready(p);if(m.type==='night')night(p,m.action,m.value);if(m.type==='vote')vote(p,m.value,m.double)}
function join(){let p=$('joinPseudo').value.trim(),code=$('roomCode').value.trim();if(!p||!code)return alert('⚠️ Entre ton pseudo et le code.');if(!code.startsWith('LG64-'))code='LG64-'+code;S.host=false;S.me=p;S.conns={};say('Connexion au salon…');makePeer(null,()=>{let c=S.peer.connect(code,{reliable:true,metadata:{pseudo:p}});S.conns.host=c;c.on('open',()=>{say('🟢 Salon trouvé…');send(c,{type:'join',pseudo:p})});c.on('data',clientMsg);c.on('error',e=>{console.error(e);alert('❌ Impossible de rejoindre : '+e.type)});c.on('close',()=>say('⚠️ Connexion fermée.'))})}
function clientMsg(m){if(m.type==='error'){alert('❌ '+m.text);return}if(m.type==='joined'||m.type==='lobby'){S.players=(m.players||[]).map(x=>({...x,peerId:null}));S.max=m.max||S.max;S.roles=m.roles||[];if(m.room)S.room=m.room;navLobby();return}if(m.type==='role'){S.game=m.game;S.game.myRole=m.role;render('role');return}if(m.type==='state'){S.game={...(S.game||{}),...m.game,myRole:(S.game||{}).myRole};render(m.mode);return}if(m.type==='prompt'){S.game={...(S.game||{}),...m.game,myRole:(S.game||{}).myRole};prompt(m.prompt,m.options||[],m.doubleAllowed);return}if(m.type==='end')end(m.winner,m.players||[])}
function save(){if(!S.host)return;let n=+$('onlinePlayerCount').textContent;if(n<S.players.length)return alert('⚠️ Trop petit pour les joueurs présents.');S.max=n;S.roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);broadcast({type:'lobby',players:pub(),max:S.max,roles:S.roles});navLobby()}
function start(){if(!S.host)return;if(S.players.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');let r=['Loup Gamer','Healer',...S.roles];r=[...new Set(r)];while(r.length<S.players.length)r.push('Joueur Gamer');r=r.slice(0,S.players.length).sort(()=>Math.random()-.5);S.players.forEach((p,i)=>{p.role=r[i];p.alive=true;p.speed=false});S.game={round:1,phase:'reveal',actions:{},victim:null,protect:null,ready:{},myRole:S.players.find(p=>p.pseudo===S.me)?.role};S.game.ready[S.me]=true;S.players.forEach(p=>{if(p.peerId)send(S.conns[p.peerId],{type:'role',role:p.role,game:{round:1,phase:'reveal',players:pub(),myRole:p.role}})});render('role')}
function ready(p){if(!p||!S.game||S.game.phase!=='reveal')return;S.game.ready[p.pseudo]=true;if(Object.keys(S.game.ready).length>=S.players.length)nightStart()}
function state(mode){broadcast({type:'state',mode,game:{round:S.game.round,phase:S.game.phase,players:pub()}})}
function nightStart(){S.game.phase='night';S.game.actions={};S.game.victim=null;S.game.protect=null;state('night');nightNext()}
function nightNext(){let w=S.players.find(p=>p.alive&&p.role==='Loup Gamer'&&!S.game.actions[p.pseudo]),h=S.players.find(p=>p.alive&&p.role==='Healer'&&!S.game.actions[p.pseudo]),p=w||h;if(!p)return resolveNight();let a=w?'wolf':'heal',o=w?alive().filter(x=>x!==p).map(x=>x.pseudo):alive().map(x=>x.pseudo);let c=p.peerId?S.conns[p.peerId]:null;if(c)send(c,{type:'prompt',prompt:a,options:o,game:{round:S.game.round,phase:'night',players:pub()}});else prompt(a,o,false)}
function night(p,a,v){if(!p||!S.game||S.game.actions[p.pseudo])return;S.game.actions[p.pseudo]={a,v};if(a==='wolf')S.game.victim=v;if(a==='heal')S.game.protect=v;nightNext()}
function resolveNight(){let v=S.players.find(p=>p.pseudo===S.game.victim);if(v&&v.pseudo!==S.game.protect)v.alive=false;S.game.phase='day';state('day');if(check())return;setTimeout(voteStart,500)}
function voteStart(){S.game.phase='vote';S.game.actions={};state('vote');alive().forEach(p=>{let o=alive().filter(x=>x!==p).map(x=>x.pseudo),c=p.peerId?S.conns[p.peerId]:null;if(c)send(c,{type:'prompt',prompt:'vote',options:o,doubleAllowed:p.role==='Speedrunner'&&!p.speed});else prompt('vote',o,p.role==='Speedrunner'&&!p.speed)})}
function vote(p,t,d){if(!p||!p.alive||S.game.actions[p.pseudo])return;S.game.actions[p.pseudo]={v:t,double:!!d};if(d)p.speed=true;if(Object.keys(S.game.actions).length>=alive().length)resolveVote()}
function resolveVote(){let c={};alive().forEach(p=>{let a=S.game.actions[p.pseudo];if(a?.v)c[a.v]=(c[a.v]||0)+(a.double?2:1)});let vals=Object.values(c),max=vals.length?Math.max(...vals):0,top=Object.keys(c).filter(x=>c[x]===max);if(top.length===1){let p=S.players.find(x=>x.pseudo===top[0]);if(p)p.alive=false}S.game.round++;if(check())return;nightStart()}
function winner(){let a=alive(),m=a.find(p=>p.role==='Manipulateur'),b=a.find(p=>p.role==='Boss Final');if(m&&a.length<=3)return'MANIPULATEUR';if(b&&a.length===1)return'BOSS FINAL';let h=a.filter(hacker).length;if(h===0)return'BONS';if(h>=a.length-h)return'HACKERS';return null}
function check(){let w=winner();if(!w)return false;let d=S.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.role}));broadcast({type:'end',winner:w,players:d});end(w,d);return true}
function render(mode){go('onlineGame');let g=S.game||{},role=g.myRole||S.game?.myRole;$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':'☀️ Jour';$('onlineAlive').textContent=(g.players||pub()).filter(p=>p.alive).length;$('onlinePlayers').innerHTML=(g.players||pub()).map(p=>`<div class="player ${p.alive?'active':'dead'}"><strong>${esc(p.pseudo)}</strong><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'}</small></div>`).join('');if(mode==='role'){$('onlineAction').innerHTML=`<div class="night-card"><h3>🎭 Ton rôle</h3><div class="role-icon">${ROLES[role]?.[0]||'🎮'}</div><h2>${esc(role||'Rôle')}</h2><button class="primary" id="readyOnline">✅ J’ai vu mon rôle</button></div>`;$('readyOnline').onclick=()=>{if(S.host)ready(S.players.find(p=>p.pseudo===S.me));else send(S.conns.host,{type:'ready'});$('onlineAction').innerHTML='<div class="message">⏳ En attente…</div>'}}else if(mode==='day')$('onlineAction').innerHTML='<div class="message">☀️ La nuit est terminée.</div>';else $('onlineAction').innerHTML='<div class="message">⏳ Attends ton action…</div>'}
function prompt(type,opts,double){go('onlineGame');$('onlineAction').innerHTML=`<div class="night-card"><h3>${type==='wolf'?'🐺 Choisis la victime':type==='heal'?'❤️‍🩹 Choisis qui protéger':'🗳️ Vote'}</h3><select id="onlineChoice"><option value="">Choisir…</option>${opts.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>${type==='vote'&&double?'<label><input id="doubleVote" type="checkbox"> ⚡ Vote double</label>':''}<button class="primary" id="onlineConfirm">✅ Valider</button></div>`;$('onlineConfirm').onclick=()=>{let v=$('onlineChoice').value;if(!v)return alert('⚠️ Choisis un joueur.');let d=$('doubleVote')?.checked||false;if(S.host){let p=S.players.find(x=>x.pseudo===S.me);type==='vote'?vote(p,v,d):night(p,type,v)}else send(S.conns.host,type==='vote'?{type:'vote',value:v,double:d}:{type:'night',action:type,value:v});$('onlineAction').innerHTML='<div class="message">⏳ Action enregistrée…</div>'}}
function end(w,ps){go('onlineEnd');let x={'BONS':['🛡️','Victoire des BONS !'],'HACKERS':['🐺','Victoire des HACKERS !'],'MANIPULATEUR':['🎭','Victoire du MANIPULATEUR !'],'BOSS FINAL':['👑','Victoire du BOSS FINAL !']}[w]||['🏆','Victoire !'];$('onlineWinnerIcon').textContent=x[0];$('onlineWinnerTitle').textContent=x[1];$('onlineFinalPlayers').innerHTML=ps.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.pseudo)}</strong><span>${ROLES[p.role]?.[0]||'🎮'} ${esc(p.role)}</span></div>`).join('')}
$('onlineBtn')?.addEventListener('click',()=>go('online'));$('createOnlineBtn')?.addEventListener('click',()=>go('onlineCreate'));$('joinOnlineBtn')?.addEventListener('click',()=>go('onlineJoin'));$('createRoomBtn')?.addEventListener('click',create);$('joinRoomBtn')?.addEventListener('click',join);$('lobbyOptionsBtn')?.addEventListener('click',()=>go('onlineOptions'));$('saveOnlineOptionsBtn')?.addEventListener('click',save);$('onlineMinusPlayers')?.addEventListener('click',()=>{$('onlinePlayerCount').textContent=Math.max(5,(+$('onlinePlayerCount').textContent||8)-1)});$('onlinePlusPlayers')?.addEventListener('click',()=>{$('onlinePlayerCount').textContent=Math.min(20,(+$('onlinePlayerCount').textContent||8)+1)});$('startOnlineGameBtn')?.addEventListener('click',start);
});