document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const ROLES={'Joueur Gamer':{icon:'🎮',team:'BONS',desc:'Aucun pouvoir.'},'Loup Gamer':{icon:'🐺',team:'HACKERS',desc:'Choisit une victime chaque nuit.'},'Healer':{icon:'❤️‍🩹',team:'BONS',desc:'Protège un joueur chaque nuit.'},'Stratège':{icon:'🧠',team:'BONS',desc:'Une fois, peut annuler une élimination par vote.'},'Support':{icon:'🤝',team:'BONS',desc:'Une fois, protège un joueur.'},'Analyste':{icon:'🔎',team:'BONS',desc:'Une fois, découvre le camp d’un joueur.'},'Speedrunner':{icon:'⚡',team:'BONS',desc:'Une fois, son vote compte double.'},'Hacker':{icon:'💻',team:'HACKERS',desc:'Une fois, bloque le pouvoir d’un joueur.'},'Saboteur':{icon:'🧨',team:'HACKERS',desc:'Une fois, déclenche un faux événement.'},'Manipulateur':{icon:'🎭',team:'SOLO',desc:'Gagne s’il est vivant lorsqu’il reste 3 joueurs.'},'Chaos':{icon:'🌀',team:'SOLO',desc:'Gagne si ses deux cibles secrètes sont éliminées.'},'Opportuniste':{icon:'🎯',team:'SOLO',desc:'Peut changer son vote deux fois et gagne avec le camp victorieux.'},'Boss Final':{icon:'👑',team:'SOLO',desc:'Gagne s’il devient le dernier joueur vivant.'},'Traître':{icon:'🗡️',team:'BONS',desc:'Devient HACKER à partir du tour 3.'}};
let net={peer:null,host:false,room:'',pseudo:'',conns:{},players:[],settings:{max:8,roles:[]},game:null};
const screen=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')};
const say=t=>{if(window.speechSynthesis){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.9;speechSynthesis.speak(u)}};
function onlineStatus(t){['onlineStatus','joinStatus'].forEach(id=>{const e=$(id);if(e)e.textContent=t})}
function send(c,m){try{if(c&&c.open)c.send(m)}catch(e){}}
function broadcast(m){Object.values(net.conns).forEach(c=>send(c,m))}
function publicPlayers(){return net.players.map(p=>({pseudo:p.pseudo,alive:p.alive}))}
function lobbyRender(){if($('roomCodeDisplay'))$('roomCodeDisplay').textContent=net.room.replace(/^Loup64-/i,'');if($('lobbyPlayers'))$('lobbyPlayers').innerHTML=net.players.map((p,i)=>`<div class="player ${i===0?'active':''}"><strong>${esc(p.pseudo)}</strong><span>${i===0?'👑 Hôte':'🟢 Joueur'}</span></div>`).join('');if($('startOnlineGameBtn'))$('startOnlineGameBtn').disabled=net.players.length<5}
function makeRoomId(){return 'Loup64-'+Math.random().toString(36).slice(2,8).toUpperCase()}
function connectPeer(id,onOpen){if(typeof Peer==='undefined'){alert('❌ Le service de connexion en ligne ne se charge pas. Recharge la page.');return}if(net.peer)try{net.peer.destroy()}catch(e){}net.peer=new Peer(id||undefined,{debug:0});net.peer.on('open',peerId=>{if(net.host)net.peer.on('connection',attachHostConnection);onOpen?.(peerId)});net.peer.on('error',e=>{const msg=e?.type==='peer-unavailable'?'Salon introuvable.':e?.type==='unavailable-id'?'Ce code est déjà utilisé. Crée une nouvelle partie.':e?.type==='network'?'Impossible de joindre le serveur. Vérifie ta connexion.':(e?.message||'Connexion impossible.');onlineStatus('❌ '+msg);if(e?.type==='peer-unavailable'||e?.type==='unavailable-id')alert('❌ '+msg)});net.peer.on('disconnected',()=>onlineStatus('⚠️ Connexion de signalisation perdue.'))}
function createRoom(){const pseudo=$('createPseudo')?.value.trim();if(!pseudo)return alert('⚠️ Entre ton pseudo.');net.host=true;net.pseudo=pseudo;net.players=[{peerId:null,pseudo,alive:true}];net.settings={max:+($('onlinePlayerCount')?.textContent||8),roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)};if(net.settings.roles.length>net.settings.max-2)return alert('⚠️ Trop de rôles spéciaux pour ce nombre de joueurs.');onlineStatus('Connexion au serveur…');connectPeer(makeRoomId(),actual=>{net.room=actual;lobbyRender();renderOnlineLobby(true);onlineStatus('🟢 Salon créé.');say('Salon créé.')})}
function attachHostConnection(conn){const pid=conn.peer;conn.on('data',msg=>hostMessage(conn,msg));conn.on('close',()=>{const p=net.players.find(x=>x.peerId===pid);if(p){delete net.conns[p.pseudo];net.players=net.players.filter(x=>x.peerId!==pid);broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});lobbyRender()}})}
function hostMessage(conn,msg){if(!msg||!net.host)return;const pseudo=pseudoFromConn(conn);if(msg.type==='join'){if(net.game)return send(conn,{type:'error',text:'La partie a déjà commencé.'});const pName=String(msg.pseudo||'').trim();if(!pName||pName.length>20||net.players.some(p=>p.pseudo.toLowerCase()===pName.toLowerCase()))return send(conn,{type:'error',text:'Pseudo déjà utilisé ou invalide.'});if(net.players.length>=net.settings.max)return send(conn,{type:'error',text:'Le salon est complet.'});const p={peerId:conn.peer,pseudo:pName,alive:true};net.players.push(p);net.conns[pName]=conn;send(conn,{type:'joined',room:net.room,players:publicPlayers(),settings:net.settings});broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});lobbyRender();return}if(msg.type==='ready'){onlineReady(pseudo);return}if(msg.type==='action'){onlineAction(pseudo,msg.action,msg.value)}}
function pseudoFromConn(c){return net.players.find(p=>p.peerId===c.peer)?.pseudo||''}
function joinRoom(){const pseudo=$('joinPseudo')?.value.trim(),raw=$('roomCode')?.value.trim().toUpperCase();if(!pseudo||!raw)return alert('⚠️ Entre ton pseudo et le code de la partie.');const code=raw.replace(/^LOUP64-/,'');if(!/^[A-Z0-9]{6}$/.test(code))return alert('⚠️ Le code doit contenir 6 caractères.');net.host=false;net.pseudo=pseudo;onlineStatus('Connexion au salon…');connectPeer(undefined,()=>{const roomId='Loup64-'+code;const conn=net.peer.connect(roomId,{reliable:true,metadata:{pseudo}});net.conns.host=conn;let opened=false;const timer=setTimeout(()=>{if(!opened){onlineStatus('❌ Délai dépassé. Vérifie le code et réessaie.');try{conn.close()}catch(e){}}},10000);conn.on('open',()=>{opened=true;clearTimeout(timer);onlineStatus('🟢 Connecté, attente du salon…');send(conn,{type:'join',pseudo})});conn.on('data',clientMessage);conn.on('close',()=>{if(!opened)return;onlineStatus('⚠️ L’hôte a fermé la connexion.');alert('⚠️ La connexion avec l’hôte est perdue.');screen('online')});conn.on('error',()=>{clearTimeout(timer);onlineStatus('❌ Erreur de connexion au salon.')})})}
function clientMessage(msg){if(!msg)return;if(msg.type==='error'){onlineStatus('❌ '+msg.text);alert('❌ '+msg.text);return}if(msg.type==='joined'){net.room=msg.room;net.players=(msg.players||[]).map(p=>({...p,peerId:null}));net.settings=msg.settings||{max:8,roles:[]};renderOnlineLobby(false);return}if(msg.type==='lobby'){net.players=msg.players||[];net.settings=msg.settings||net.settings;renderOnlineLobby(false);return}if(msg.type==='privateRole'){net.game=net.game||{};net.game.role=msg.role;net.game.team=msg.team;net.game.chaosTargets=msg.chaosTargets||[];renderOnlineGame('role');return}if(msg.type==='game'){const old=net.game||{};net.game={...msg.game,role:old.role,team:old.team,chaosTargets:old.chaosTargets||[]};renderOnlineGame(msg.mode||'public');return}if(msg.type==='actionPrompt'){renderPrompt(msg.prompt,msg.options||[],msg.extra||{});return}if(msg.type==='notice'){onlineStatus(msg.text);if(msg.speak)say(msg.text);return}if(msg.type==='end'){renderOnlineEnd(msg.winner,msg.players||[]);return}}
function renderOnlineLobby(host){lobbyRender();if($('lobbyOptionsBtn'))$('lobbyOptionsBtn').style.display=host?'block':'none';if($('startOnlineGameBtn'))$('startOnlineGameBtn').style.display=host?'block':'none';screen('onlineLobby')}
function saveOptions(){if(!net.host)return;const max=+$('onlinePlayerCount').textContent||8,roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);if(net.players.length>max)return alert('⚠️ Le maximum est inférieur au nombre de joueurs présents.');if(roles.length>max-2)return alert('⚠️ Trop de rôles spéciaux pour ce nombre de joueurs.');net.settings={max,roles};broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});renderOnlineLobby(true)}
function rolePool(){let r=['Loup Gamer','Healer'];for(const x of net.settings.roles)if(!r.includes(x))r.push(x);while(r.length<net.players.length)r.push('Joueur Gamer');return r.slice(0,net.players.length)}
function startOnline(){if(!net.host)return;if(net.players.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');if(net.settings.roles.length>net.players.length-2)return alert('⚠️ Trop de rôles spéciaux.');const names=rolePool();for(let i=names.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[names[i],names[j]]=[names[j],names[i]]}net.players.forEach((p,i)=>{p.alive=true;p.roleName=names[i];p.role=ROLES[names[i]];p.powerUsed=false;p.doubleUsed=false;p.voteChanges=0;p.chaosTargets=[]});const chaos=net.players.find(p=>p.roleName==='Chaos');if(chaos){const pool=net.players.filter(p=>p!==chaos);for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}chaos.chaosTargets=pool.slice(0,2).map(p=>p.pseudo)}net.game={round:1,phase:'reveal',nightVictim:null,nightProtect:null,supportProtect:null,blockedPower:null,actions:{},ready:{}};net.players.forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'privateRole',role:p.roleName,team:dynamicTeam(p),chaosTargets:p.roleName==='Chaos'?p.chaosTargets:[]})});broadcastGame('reveal');renderOnlineGame('reveal')}
function dynamicTeam(p){return p.roleName==='Traître'&&net.game&&net.game.round>=3?'HACKERS':p.role.team}
function isHacker(p){return !!p&&(p.roleName==='Loup Gamer'||p.roleName==='Hacker'||p.roleName==='Saboteur'||(p.roleName==='Traître'&&net.game.round>=3))}
function broadcastGame(mode){const pub={round:net.game.round,phase:net.game.phase,players:publicPlayers(),victim:net.game.nightVictim,protected:net.game.nightProtect,supportProtected:net.game.supportProtect,blockedPower:net.game.blockedPower};broadcast({type:'game',game:pub,mode})}
function renderOnlineGame(mode){screen('onlineGame');const g=net.game||{};$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':'☀️ Jour';const list=g.players||publicPlayers();$('onlineAlive').textContent=list.filter(p=>p.alive).length;$('onlinePlayers').innerHTML=list.map(p=>`<div class="player ${p.alive?'active':'dead'}"><strong>${esc(p.pseudo)}</strong><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'}</small></div>`).join('');if(mode==='role'||mode==='reveal'){const myRole=g.role||net.players.find(p=>p.pseudo===net.pseudo)?.roleName||'Joueur Gamer';let extra='';if(myRole==='Chaos'&&(g.chaosTargets||[]).length===2)extra=`<p>🎯 Tes cibles secrètes : <b>${esc(g.chaosTargets[0])}</b> et <b>${esc(g.chaosTargets[1])}</b>.</p>`;$('onlineAction').innerHTML=`<div class="night-card"><h3>🎭 Ton rôle</h3><div class="role-icon">${ROLES[myRole]?.icon||'🎮'}</div><h3>${esc(myRole)}</h3><p>${esc(ROLES[myRole]?.desc||'')}</p>${extra}<button class="primary" id="onlineReadyBtn">✅ J’ai vu mon rôle</button></div>`;$('onlineReadyBtn').onclick=()=>{if(net.host)onlineReady(net.pseudo);else send(net.conns.host,{type:'ready'});$('onlineAction').innerHTML='<div class="message">⏳ En attente des autres joueurs…</div>'};return}if(net.host)hostNextUI();else $('onlineAction').innerHTML='<div class="message">⏳ Attends l’action du jeu…</div>'}
function onlineReady(pseudo){if(!net.host||!net.game||net.game.phase!=='reveal')return;if(net.game.ready[pseudo])return;net.game.ready[pseudo]=true;if(Object.keys(net.game.ready).length===net.players.length)startNight();else broadcast({type:'notice',text:`${pseudo} est prêt.`})}
function blockedRole(roleName){return !!net.game.blockedPower&&roleName===net.game.blockedPower}
function startNight(){net.game.phase='night';net.game.actions={};net.game.nightVictim=null;net.game.nightProtect=null;net.game.supportProtect=null;net.game.blockedPower=null;broadcastGame('night');hostNextNight()}
function hostNextNight(){if(!net.host)return;const order=['Hacker','Saboteur','Analyste','Support','Loup Gamer','Traître','Healer'];for(const roleName of order){const p=net.players.find(x=>x.alive&&x.roleName===roleName&&!net.game.actions[x.pseudo]);if(!p||blockedRole(roleName))continue;if(roleName==='Hacker')return promptHost(p,'block',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo&&['Loup Gamer','Healer','Analyste','Support'].includes(x.roleName)).map(x=>x.pseudo));if(roleName==='Saboteur')return promptHost(p,'sabotage',[]);if(roleName==='Analyste')return promptHost(p,'analyse',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo));if(roleName==='Support'&&!p.powerUsed)return promptHost(p,'support',net.players.filter(x=>x.alive).map(x=>x.pseudo));if(['Loup Gamer','Traître'].includes(roleName))return promptHost(p,'wolf',net.players.filter(x=>x.alive&&!['Loup Gamer','Healer'].includes(x.roleName)).map(x=>x.pseudo));if(roleName==='Healer')return promptHost(p,'protect',net.players.filter(x=>x.alive).map(x=>x.pseudo))}resolveNight()}
function promptHost(p,prompt,options){const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt,options});else renderPrompt(prompt,options)}
function renderPrompt(prompt,options){const labels={wolf:'🐺 Choisis la victime',protect:'❤️‍🩹 Choisis qui protéger',block:'💻 Choisis le pouvoir à bloquer',analyse:'🔎 Choisis qui analyser',support:'🤝 Choisis qui protéger',sabotage:'🧨 Déclenche ton faux événement',strategy:'🧠 Utiliser le pouvoir du Stratège ?',vote:'🗳️ Choisis qui éliminer'};let html=`<div class="night-card"><h3>${labels[prompt]||'Action'}</h3>`;if(prompt==='block')html+=`<p>Bloque un pouvoir, pas le joueur.</p>`;if(prompt==='sabotage')html+=`<p>Les autres recevront une fausse alerte.</p>`;if(options.length)html+=`<select id="onlineChoice"><option value="">Choisir…</option>${options.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;if(prompt==='vote'&&net.game?.role==='Speedrunner')html+=`<label class="role-option"><input type="checkbox" id="doubleVote"> ⚡ Utiliser mon vote double</label>`;html+=`<button class="primary" id="onlineActionBtn">${prompt==='sabotage'?'🧨 Déclencher':'✅ Valider'}</button></div>`;$('onlineAction').innerHTML=html;$('onlineActionBtn').onclick=()=>{let v=$('onlineChoice')?.value||true;if(options.length&&!v)return alert('⚠️ Choisis une option.');const extra=prompt==='vote'?!!$('doubleVote')?.checked:false;const action={prompt,value:v,double:extra};if(net.host)onlineAction(net.pseudo,action);else send(net.conns.host,{type:'action',action})}}
function onlineAction(pseudo,action,value){if(!net.host||!net.game)return;const p=net.players.find(x=>x.pseudo===pseudo);if(!p||!p.alive)return;const a=action&&action.prompt?action:{prompt:action,value};const allowed=['wolf','protect','block','analyse','support','sabotage','vote','strategy'];if(!allowed.includes(a.prompt))return;if(net.game.phase==='reveal'||(net.game.phase==='night'&&!['vote','strategy'].includes(a.prompt))||(net.game.phase==='vote'&&['vote','strategy'].includes(a.prompt))){if(net.game.actions[pseudo]&&a.prompt!=='vote')return}
if(a.prompt==='strategy'){if(p.roleName!=='Stratège'||net.game.phase!=='vote'||p.powerUsed||!net.game.pendingVoteVictim)return;p.powerUsed=true;const victim=net.players.find(x=>x.pseudo===net.game.pendingVoteVictim);if(a.value!=='Annuler l’élimination'&&victim)victim.alive=false;net.game.pendingVoteVictim=null;finishVoteRound();return}
if(a.prompt==='vote'){if(net.game.phase!=='vote'||net.game.actions[pseudo])return;const target=net.players.find(x=>x.pseudo===a.value);if(!target||!target.alive||target.pseudo===pseudo)return;if(a.double&&p.roleName==='Speedrunner'&&!p.doubleUsed){p.doubleUsed=true}net.game.actions[pseudo]={prompt:'vote',value:target.pseudo,double:!!a.double};if(p.roleName==='Opportuniste'&&p.voteChanges<2)p.voteChanges++;broadcastGame('vote');if(net.players.filter(x=>x.alive).every(x=>net.game.actions[x.pseudo]))resolveVote();return}
if(net.game.phase!=='night'||net.game.actions[pseudo]||blockedRole(p.roleName))return;
if(a.prompt==='block'){if(p.roleName!=='Hacker'||p.powerUsed)return;const target=net.players.find(x=>x.pseudo===a.value);if(!target||!['Loup Gamer','Healer','Analyste','Support'].includes(target.roleName))return;p.powerUsed=true;net.game.blockedPower=target.roleName}
if(a.prompt==='sabotage'){if(p.roleName!=='Saboteur'||p.powerUsed)return;p.powerUsed=true;broadcast({type:'notice',text:'🚨 Une fausse alerte a été déclenchée cette nuit.',speak:false})}
if(a.prompt==='analyse'){if(p.roleName!=='Analyste'||p.powerUsed)return;const t=net.players.find(x=>x.pseudo===a.value);if(!t)return;p.powerUsed=true;const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'notice',text:`🔎 ${t.pseudo} est ${isHacker(t)?'HACKER':'BON'}.`})}
if(a.prompt==='support'){if(p.roleName!=='Support'||p.powerUsed)return;if(!net.players.some(x=>x.pseudo===a.value&&x.alive))return;p.powerUsed=true;net.game.supportProtect=a.value}
if(a.prompt==='wolf'){if(!['Loup Gamer','Traître'].includes(p.roleName)||blockedRole(p.roleName))return;const t=net.players.find(x=>x.pseudo===a.value);if(!t||!t.alive||['Loup Gamer','Healer'].includes(t.roleName))return;net.game.nightVictim=a.value}
if(a.prompt==='protect'){if(p.roleName!=='Healer'||blockedRole(p.roleName))return;if(!net.players.some(x=>x.pseudo===a.value&&x.alive))return;net.game.nightProtect=a.value}
net.game.actions[pseudo]=a;broadcastGame('night');hostNextNight()}
function resolveNight(){const v=net.players.find(p=>p.pseudo===net.game.nightVictim);if(v&&v.pseudo!==net.game.nightProtect&&v.pseudo!==net.game.supportProtect)v.alive=false;net.game.phase='day';broadcastGame('day');if(checkOnlineEnd())return;setTimeout(startVote,700)}
function startVote(){if(!net.host)return;net.game.phase='vote';net.game.actions={};broadcastGame('vote');const alive=net.players.filter(p=>p.alive);alive.forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;const opts=alive.filter(x=>x.pseudo!==p.pseudo).map(x=>x.pseudo);if(c)send(c,{type:'actionPrompt',prompt:'vote',options:opts});else renderPrompt('vote',opts)});}
function resolveVote(){const counts={};net.players.filter(p=>p.alive).forEach(p=>{const a=net.game.actions[p.pseudo];if(a?.prompt==='vote'&&a.value)counts[a.value]=(counts[a.value]||0)+(a.double&&p.roleName==='Speedrunner'?2:1)});const vals=Object.values(counts),max=vals.length?Math.max(...vals):0,tops=Object.keys(counts).filter(k=>counts[k]===max);if(tops.length===1){const victim=net.players.find(p=>p.pseudo===tops[0]);const strat=net.players.find(p=>p.alive&&p.roleName==='Stratège'&&!p.powerUsed);if(strat){net.game.pendingVoteVictim=victim.pseudo;const c=strat.peerId?net.conns[strat.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt:'strategy',options:['Annuler l’élimination','Ne rien faire']});else renderPrompt('strategy',['Annuler l’élimination','Ne rien faire']);return}victim.alive=false}finishVoteRound()}
function finishVoteRound(){net.game.round++;if(checkOnlineEnd())return;startNight()}
function checkOnlineEnd(){const a=net.players.filter(p=>p.alive);const m=a.find(p=>p.roleName==='Manipulateur'),c=a.find(p=>p.roleName==='Chaos'),b=a.find(p=>p.roleName==='Boss Final');let winner=null;if(m&&a.length<=3)winner='MANIPULATEUR';else if(c&&c.chaosTargets?.length===2&&c.chaosTargets.every(n=>!net.players.find(p=>p.pseudo===n)?.alive))winner='CHAOS';else if(b&&a.length===1)winner='BOSS FINAL';else{const h=a.filter(isHacker).length;const nonH=a.filter(p=>!isHacker(p)&&!['Manipulateur','Chaos','Boss Final'].includes(p.roleName)).length;if(h===0)winner='BONS';else if(h>=nonH&&nonH>0)winner='HACKERS'}if(!winner)return false;const final=net.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.roleName}));broadcast({type:'end',winner,players:final});renderOnlineEnd(winner,final);return true}
function hostNextUI(){if(net.game?.phase==='reveal')renderOnlineGame('reveal');else renderOnlineGame('public')}
function renderOnlineEnd(w,players){screen('onlineEnd');const map={BONS:['🛡️','Victoire des BONS !'],HACKERS:['🐺','Victoire des HACKERS !'],MANIPULATEUR:['🎭','Victoire du MANIPULATEUR !'],CHAOS:['🌀','Victoire du CHAOS !'],'BOSS FINAL':['👑','Victoire du BOSS FINAL !']};const x=map[w]||['🏆','Victoire !'];$('onlineWinnerIcon').textContent=x[0];$('onlineWinnerTitle').textContent=x[1];$('onlineFinalPlayers').innerHTML=players.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.pseudo)}</strong><span>${ROLES[p.role]?.icon||'🎮'} ${esc(p.role)}</span></div>`).join('')}
$('onlineBtn')?.addEventListener('click',()=>screen('online'));$('createOnlineBtn')?.addEventListener('click',()=>screen('onlineCreate'));$('joinOnlineBtn')?.addEventListener('click',()=>screen('onlineJoin'));$('createRoomBtn')?.addEventListener('click',createRoom);$('joinRoomBtn')?.addEventListener('click',joinRoom);$('lobbyOptionsBtn')?.addEventListener('click',()=>screen('onlineOptions'));$('saveOnlineOptionsBtn')?.addEventListener('click',saveOptions);$('startOnlineGameBtn')?.addEventListener('click',startOnline);$('onlineMinusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.max(5,+e.textContent-1)});$('onlinePlusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.min(20,+e.textContent+1)});document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen||'home')));
});