document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>'\" ]/g,c=>({'&':'&','<':'<','>':'>',"'":'&#39;','\"':'"'}[c]));
const ROLES={
'Joueur Gamer':{icon:'🎮',team:'BONS',desc:'Aucun pouvoir.'},'Loup Gamer':{icon:'🐺',team:'HACKERS',desc:'Choisit une victime chaque nuit.'},'Healer':{icon:'❤️‍🩹',team:'BONS',desc:'Protège un joueur chaque nuit.'},'Stratège':{icon:'🧠',team:'BONS',desc:'Une fois, peut annuler une élimination par vote.'},'Support':{icon:'🤝',team:'BONS',desc:'Une fois, protège un joueur.'},'Analyste':{icon:'🔎',team:'BONS',desc:'Une fois, découvre le camp d’un joueur.'},'Speedrunner':{icon:'⚡',team:'BONS',desc:'Une fois, son vote compte double.'},'Hacker':{icon:'💻',team:'HACKERS',desc:'Une fois, bloque le pouvoir d’un joueur.'},'Saboteur':{icon:'🧨',team:'HACKERS',desc:'Une fois, déclenche un faux événement.'},'Manipulateur':{icon:'🎭',team:'SOLO',desc:'Gagne s’il est vivant à 3 joueurs.'},'Chaos':{icon:'🌀',team:'SOLO',desc:'Gagne si ses deux cibles secrètes sont éliminées.'},'Opportuniste':{icon:'🎯',team:'SOLO',desc:'Peut changer son vote deux fois et gagne avec le camp victorieux.'},'Boss Final':{icon:'👑',team:'SOLO',desc:'Gagne s’il devient le dernier joueur vivant.'},'Traître':{icon:'🗡️',team:'BONS',desc:'Devient HACKER à partir du tour 3.'}
};
let net={peer:null,host:false,room:'',pseudo:'',conns:{},players:[],settings:{max:8,roles:[]},game:null};
const screen=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')};
const say=t=>{if(window.speechSynthesis){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.9;speechSynthesis.speak(u)}};
function onlineStatus(t){const e=$('onlineStatus');if(e)e.textContent=t}
function send(conn,msg){if(conn&&conn.open)conn.send(msg)}
function broadcast(msg){Object.values(net.conns).forEach(c=>send(c,msg))}
function publicPlayers(){return net.players.map(p=>({pseudo:p.pseudo,alive:p.alive}))}
function lobbyRender(){if($('roomCodeDisplay'))$('roomCodeDisplay').textContent=net.room.replace(/^Loup64-/,'');if($('lobbyPlayers'))$('lobbyPlayers').innerHTML=net.players.map((p,i)=>'<div class="player '+(i===0?'active':'')+'"><strong>'+esc(p.pseudo)+'</strong><span>'+(i===0?'👑 Hôte':'🟢 Joueur')+'</span></div>').join('');if($('startOnlineGameBtn'))$('startOnlineGameBtn').disabled=net.players.length<5;}
function connectPeer(id,onOpen){
 if(net.peer)try{net.peer.destroy()}catch(e){}
 net.peer=new Peer(id||undefined,{host:'0.peerjs.com',port:443,path:'/',secure:true,debug:2,config:{iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun2.l.google.com:19302'},{urls:'turn:openrelay.metered.ca:80',username:'openrelayproject',credential:'openrelayproject'},{urls:'turn:openrelay.metered.ca:443',username:'openrelayproject',credential:'openrelayproject'},{urls:'turn:openrelay.metered.ca:443?transport=tcp',username:'openrelayproject',credential:'openrelayproject'}]}});
 net.peer.on('error',e=>{console.error('[PEER ERROR]',e.type,e);const map={'peer-unavailable':"Salon introuvable. L'hôte doit rester sur le salon.",'unavailable-id':'Code déjà pris.','network':'Impossible de joindre 0.peerjs.com.','server-error':'Serveur PeerJS en panne.','socket-error':'Erreur socket.','socket-closed':'Socket fermée.','webrtc':'WebRTC bloqué.'};const msg=map[e.type]||(e.type+': '+(e.message||'erreur'));onlineStatus('❌ '+msg);const js=document.getElementById('joinStatus');if(js)js.textContent='❌ '+msg;if(e.type!=='peer-unavailable')try{alert('❌ '+msg)}catch(x){}});
 net.peer.on('disconnected',()=>{onlineStatus('⚠️ Signalisation perdue…');try{net.peer.reconnect()}catch(e){}});
 net.peer.on('open',peerId=>{console.log('[PEER OPEN]',peerId);if(net.host)net.peer.on('connection',conn=>{console.log('[HOST] incoming',conn.peer);attachHostConnection(conn)});if(onOpen)onOpen(peerId)});
}
function createRoom(){const pseudo=$('createPseudo').value.trim();if(!pseudo)return alert('⚠️ Entre ton pseudo.');net.host=true;net.pseudo=pseudo;net.players=[{peerId:null,pseudo,alive:true}];net.settings={max:+($('onlinePlayerCount')?.textContent||8),roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)};onlineStatus('Connexion…');const id='Loup64-'+Math.random().toString(36).slice(2,8).toUpperCase();connectPeer(id,actual=>{net.room=actual;lobbyRender();screen('onlineLobby');onlineStatus('🟢 Salon prêt — reste ici, partage le code.');say('Salon créé.');});}
function attachHostConnection(conn){const pid=conn.peer;conn.on('open',()=>{});conn.on('data',msg=>hostMessage(conn,msg));conn.on('close',()=>{const p=net.players.find(x=>x.peerId===pid);if(p){net.players=net.players.filter(x=>x.peerId!==pid);delete net.conns[p.pseudo];lobbyRender();broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});}})}
function hostMessage(conn,msg){if(!msg||!net.host)return;if(msg.type==='join'){if(net.game)return send(conn,{type:'error',text:'Partie déjà commencée.'});const pseudo=String(msg.pseudo||'').trim();if(!pseudo||net.players.some(p=>p.pseudo.toLowerCase()===pseudo.toLowerCase()))return send(conn,{type:'error',text:'Pseudo invalide ou pris.'});if(net.players.length>=net.settings.max)return send(conn,{type:'error',text:'Salon complet.'});const p={peerId:conn.peer,pseudo,alive:true};net.players.push(p);net.conns[pseudo]=conn;send(conn,{type:'joined',room:net.room,host:true,players:publicPlayers(),settings:net.settings});broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});lobbyRender();return}if(msg.type==='action')onlineAction(pseudoFromConn(conn),msg.action,msg.value);if(msg.type==='ready')onlineReady(pseudoFromConn(conn))}
function pseudoFromConn(conn){return net.players.find(p=>p.peerId===conn.peer)?.pseudo||''}
function joinRoom(){const pseudo=$('joinPseudo').value.trim();let code=$('roomCode').value.trim();if(!pseudo||!code)return alert('⚠️ Pseudo + code requis.');code=code.replace(/\s+/g,'').toUpperCase();if(code.startsWith('LOUP64-'))code=code.slice(7);if(!code||code.length<4)return alert('⚠️ Code trop court.');const peerId='Loup64-'+code;net.host=false;net.pseudo=pseudo;const setStatus=t=>{console.log('[STATUS]',t);onlineStatus(t);const js=document.getElementById('joinStatus');if(js)js.textContent=t};let attempt=0;const maxAttempts=4;function tryConnect(){attempt++;setStatus('Connexion… essai '+attempt+'/'+maxAttempts+' → '+peerId);connectPeer(undefined,()=>{console.log('[JOIN]',peerId);const conn=net.peer.connect(peerId,{reliable:true,serialization:'json',metadata:{pseudo}});net.conns.host=conn;let opened=false,failed=false;const timeout=setTimeout(()=>{if(opened)return;failed=true;try{conn.close()}catch(e){}if(attempt<maxAttempts){setStatus('Timeout, nouvel essai…');setTimeout(tryConnect,1200);return}const msg='❌ Échec. Code exact ? Hôte sur le salon ? URL = loison64.github.io ?';setStatus(msg);alert(msg)},12000);conn.on('open',()=>{opened=true;clearTimeout(timeout);setStatus('Connecté !');send(conn,{type:'join',pseudo})});conn.on('data',clientMessage);conn.on('close',()=>{if(!opened||failed)return;setStatus('⚠️ Hôte déconnecté.');alert('⚠️ Connexion perdue.');screen('online')});conn.on('error',err=>{console.error('[CONN]',err);clearTimeout(timeout);if(!opened){failed=true;if(attempt<maxAttempts)setTimeout(tryConnect,1200);else setStatus('❌ Erreur: '+(err&&err.type||err||'?'))}})})}tryConnect()}
function clientMessage(msg){console.log('[CLIENTMSG]',msg.type);if(msg.type==='error'){onlineStatus('❌ '+msg.text);alert('❌ '+msg.text);return}if(msg.type==='joined'){net.room=msg.room;net.players=msg.players.map(p=>({...p,peerId:null}));net.settings=msg.settings;renderOnlineLobby(false);return}if(msg.type==='lobby'){net.players=msg.players;net.settings=msg.settings;renderOnlineLobby(false);return}if(msg.type==='privateRole'){net.game=net.game||{};net.game.role=msg.role;net.game.team=msg.team;renderOnlineGame('role');return}if(msg.type==='game'){net.game=msg.game;renderOnlineGame(msg.mode||'public');return}if(msg.type==='actionPrompt'){renderPrompt(msg.prompt,msg.options||[]);return}if(msg.type==='notice'){onlineStatus(msg.text);if(msg.speak)say(msg.text);return}if(msg.type==='end'){renderOnlineEnd(msg.winner,msg.players);return}}
function renderOnlineLobby(host){lobbyRender();if($('lobbyOptionsBtn'))$('lobbyOptionsBtn').style.display=host?'block':'none';if($('startOnlineGameBtn'))$('startOnlineGameBtn').style.display=host?'block':'none';screen('onlineLobby')}
function saveOptions(){if(!net.host)return;net.settings.max=+($('onlinePlayerCount').textContent||8);net.settings.roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});renderOnlineLobby(true)}
function rolePool(){let r=['Loup Gamer','Healer'];net.settings.roles.forEach(x=>{if(x!=='Joueur Gamer')r.push(x)});while(r.length<net.players.length)r.push('Joueur Gamer');return r.slice(0,net.players.length)}
function startOnline(){if(!net.host)return;if(net.players.length<5)return alert('⚠️ Min 5 joueurs.');let names=rolePool();for(let i=names.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[names[i],names[j]]=[names[j],names[i]]}net.players.forEach((p,i)=>{p.alive=true;p.roleName=names[i];p.role=ROLES[names[i]];p.voted=null;p.doubleUsed=false;p.powerUsed=false;p.blocked=false;p.protected=false;p.chaosTargets=[]});const chaos=net.players.find(p=>p.roleName==='Chaos');if(chaos){let o=net.players.filter(p=>p!==chaos).sort(()=>Math.random()-.5);chaos.chaosTargets=o.slice(0,2).map(p=>p.pseudo)}net.game={round:1,phase:'reveal',nightVictim:null,nightProtect:null,supportProtect:null,blocked:null,actions:{},ready:{}};net.players.forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'privateRole',role:p.roleName,team:dynamicTeam(p)})});broadcastGame('reveal');renderOnlineGame('reveal')}
function dynamicTeam(p){return p.roleName==='Traître'&&net.game&&net.game.round>=3?'HACKERS':p.role.team}
function broadcastGame(mode){broadcast({type:'game',game:{round:net.game.round,phase:net.game.phase,players:publicPlayers(),victim:net.game.nightVictim,protected:net.game.nightProtect,blocked:net.game.blocked},mode})}
function renderOnlineGame(mode){screen('onlineGame');const g=net.game||{};$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':'☀️ Jour';$('onlineAlive').textContent=(g.players||publicPlayers()).filter(p=>p.alive).length;$('onlinePlayers').innerHTML=(g.players||publicPlayers()).map(p=>'<div class="player '+(p.alive?'active':'dead')+'"><strong>'+esc(p.pseudo)+'</strong><small>'+(p.alive?'🟢 Vivant':'⚫ Éliminé')+'</small></div>').join('');if(mode==='role'||mode==='reveal'){const myRole=mode==='role'?net.game.role:(net.players.find(p=>p.pseudo===net.pseudo)?.roleName);$('onlineAction').innerHTML='<div class="night-card"><h3>🎭 Ton rôle</h3><div class="role-icon">'+(ROLES[myRole]?.icon||'🎮')+'</div><h3>'+esc(myRole||'?')+'</h3><p>'+esc(ROLES[myRole]?.desc||'')+'</p><button class="primary" id="onlineReadyBtn">✅ J’ai vu mon rôle</button></div>';$('onlineReadyBtn').onclick=()=>{if(net.host)onlineReady(net.pseudo);else send(net.conns.host,{type:'ready'});$('onlineAction').innerHTML='<div class="message">⏳ En attente…</div>'};return}if(net.host)hostNextUI();else $('onlineAction').innerHTML='<div class="message">⏳ Attends…</div>'}
function onlineReady(pseudo){if(!net.host||!net.game)return;net.game.ready[pseudo]=true;if(Object.keys(net.game.ready).length===net.players.length)startNight();else broadcast({type:'notice',text:pseudo+' est prêt.'})}
function startNight(){net.game.phase='night';net.game.actions={};net.game.nightVictim=null;net.game.nightProtect=null;net.game.supportProtect=null;net.game.blocked=null;net.game.ready={};broadcastGame('night');hostNextNight()}
function hostNextNight(){if(!net.host)return;const simple=['Hacker','Saboteur','Analyste','Support','Healer'];const pending=simple.find(r=>net.players.find(x=>x.alive&&x.roleName===r&&!net.game.actions[x.pseudo]));if(pending){const p=net.players.find(x=>x.alive&&x.roleName===pending&&!net.game.actions[x.pseudo]);if(pending==='Healer')return promptHost(p,'protect',net.players.filter(x=>x.alive).map(x=>x.pseudo));if(pending==='Hacker')return promptHost(p,'block',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo));if(pending==='Analyste')return promptHost(p,'analyse',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo));if(pending==='Support')return promptHost(p,'support',net.players.filter(x=>x.alive).map(x=>x.pseudo));if(pending==='Saboteur')return promptHost(p,'sabotage',[])}const wolf=net.players.find(x=>x.alive&&x.roleName==='Loup Gamer');const traitor=net.players.find(x=>x.alive&&x.roleName==='Traître'&&net.game.round>=3);const actor=wolf||traitor;if(actor&&!net.game.actions[actor.pseudo])return promptHost(actor,'wolf',net.players.filter(x=>x.alive&&x.pseudo!==actor.pseudo&&x.roleName!=='Healer'&&x.roleName!=='Loup Gamer'&&!(x.roleName==='Traître'&&net.game.round>=3)).map(x=>x.pseudo));resolveNight()}
function promptHost(p,prompt,options){const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt,options});else renderPrompt(prompt,options)}
function renderPrompt(prompt,options){const labels={wolf:'🐺 Victime',protect:'❤️‍🩹 Protéger',block:'💻 Bloquer',analyse:'🔎 Analyser',support:'🤝 Protéger',sabotage:'🧨 Sabotage',strategy:'🧠 Annuler ?',vote:'🗳️ Éliminer'};let html='<div class="night-card"><h3>'+(labels[prompt]||'Action')+'</h3>';if(options.length)html+='<select id="onlineChoice"><option value="">Choisir…</option>'+options.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')+'</select>';html+='<button class="primary" id="onlineActionBtn">✅ Valider</button></div>';$('onlineAction').innerHTML=html;$('onlineActionBtn').onclick=()=>{let v=$('onlineChoice')?.value||true;if(options.length&&!v)return alert('⚠️ Choisis.');if(net.host){onlineAction(net.pseudo,{prompt,value:v});$('onlineAction').innerHTML='<div class="message">⏳ …</div>'}else send(net.conns.host,{type:'action',action:{prompt,value:v}})}}
function onlineAction(pseudo,action,value){if(!net.host||!net.game)return;const p=net.players.find(x=>x.pseudo===pseudo);if(!p||!p.alive)return;const a=action&&action.prompt?action:{prompt:action,value};if(a.prompt==='strategy'){if(net.game.phase!=='vote'||net.game.pendingVoteVictim==null)return;const victim=net.players.find(x=>x.pseudo===net.game.pendingVoteVictim);if(victim&&a.value!=='Annuler l’élimination')victim.alive=false;net.game.pendingVoteVictim=null;return finishVoteRound()}if(a.prompt==='vote')return onlineVote(pseudo,a.value);if(net.game.phase!=='night'||net.game.actions[pseudo])return;net.game.actions[pseudo]=a;if(a.prompt==='wolf')net.game.nightVictim=a.value;if(a.prompt==='protect')net.game.nightProtect=a.value;if(a.prompt==='support')net.game.supportProtect=a.value;if(a.prompt==='block')net.game.blocked=a.value;if(a.prompt==='analyse'){const t=net.players.find(x=>x.pseudo===a.value);const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'notice',text:'🔎 '+a.value+' est '+(isHacker(t)?'HACKER':'BON')})}if(a.prompt==='sabotage')broadcast({type:'notice',text:'🚨 Fausse alerte.',speak:false});broadcastGame('night');hostNextNight()}
function isHacker(p){return p&&(p.roleName==='Loup Gamer'||p.roleName==='Hacker'||p.roleName==='Saboteur'||(p.roleName==='Traître'&&net.game.round>=3))}
function resolveNight(){const v=net.players.find(p=>p.pseudo===net.game.nightVictim);if(v&&v.pseudo!==net.game.nightProtect&&v.pseudo!==net.game.supportProtect&&net.game.blocked!==v.pseudo)v.alive=false;net.game.phase='day';broadcastGame('day');if(checkOnlineEnd())return;setTimeout(()=>startVote(),700)}
function startVote(){net.game.phase='vote';net.game.actions={};broadcastGame('vote');net.players.filter(p=>p.alive).forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt:'vote',options:net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo)})});if(net.players.find(p=>p.alive&&!p.peerId))renderPrompt('vote',net.players.filter(x=>x.alive&&x.pseudo!==net.pseudo).map(x=>x.pseudo))}
function resolveVote(){const counts={};net.players.filter(p=>p.alive).forEach(p=>{const a=net.game.actions[p.pseudo];if(a?.prompt==='vote'&&a.value)counts[a.value]=(counts[a.value]||0)+1});const max=Math.max(0,...Object.values(counts));const tops=Object.keys(counts).filter(k=>counts[k]===max);if(tops.length===1){const victim=net.players.find(p=>p.pseudo===tops[0]);const strat=net.players.find(p=>p.alive&&p.roleName==='Stratège'&&!p.powerUsed);if(strat){strat.powerUsed=true;net.game.pendingVoteVictim=victim.pseudo;const opts=['Annuler l’élimination','Ne rien faire'];const c=strat.peerId?net.conns[strat.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt:'strategy',options:opts});else renderPrompt('strategy',opts);return}victim.alive=false}finishVoteRound()}
function finishVoteRound(){net.game.round++;if(!checkOnlineEnd())startNight()}
function onlineVote(pseudo,value){if(!net.host||!net.game||net.game.phase!=='vote')return;const p=net.players.find(x=>x.pseudo===pseudo);if(!p||!p.alive||net.game.actions[pseudo])return;net.game.actions[pseudo]={prompt:'vote',value};if(net.players.filter(x=>x.alive).every(x=>net.game.actions[x.pseudo]))resolveVote()}
function checkOnlineEnd(){const a=net.players.filter(p=>p.alive);const m=a.find(p=>p.roleName==='Manipulateur'),c=a.find(p=>p.roleName==='Chaos'),b=a.find(p=>p.roleName==='Boss Final');let winner=null;if(m&&a.length<=3)winner='MANIPULATEUR';else if(c&&c.chaosTargets?.length===2&&c.chaosTargets.every(n=>!net.players.find(p=>p.pseudo===n)?.alive))winner='CHAOS';else if(b&&a.length===1)winner='BOSS FINAL';else{const h=a.filter(isHacker).length;if(h===0)winner='BONS';else if(h>=a.length-h)winner='HACKERS'}if(!winner)return false;const list=net.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.roleName}));broadcast({type:'end',winner,players:list});renderOnlineEnd(winner,list);return true}
function hostNextUI(){renderOnlineGame(net.game.phase==='reveal'?'reveal':'public')}
function renderOnlineEnd(w,players){screen('onlineEnd');const map={BONS:['🛡️','Victoire des BONS !'],HACKERS:['🐺','Victoire des HACKERS !'],MANIPULATEUR:['🎭','Victoire du MANIPULATEUR !'],CHAOS:['🌀','Victoire du CHAOS !'],'BOSS FINAL':['👑','Victoire du BOSS FINAL !']};const x=map[w]||['🏆','Victoire !'];$('onlineWinnerIcon').textContent=x[0];$('onlineWinnerTitle').textContent=x[1];$('onlineFinalPlayers').innerHTML=players.map(p=>'<div class="final-player '+(p.alive?'':'dead')+'"><strong>'+(p.alive?'🟢':'⚫')+' '+esc(p.pseudo)+'</strong><span>'+(ROLES[p.role]?.icon||'🎮')+' '+esc(p.role)+'</span></div>').join('')}
$('onlineBtn')?.addEventListener('click',()=>screen('online'));
$('createOnlineBtn')?.addEventListener('click',()=>screen('onlineCreate'));
$('joinOnlineBtn')?.addEventListener('click',()=>screen('onlineJoin'));
$('createRoomBtn')?.addEventListener('click',createRoom);
$('joinRoomBtn')?.addEventListener('click',joinRoom);
$('lobbyOptionsBtn')?.addEventListener('click',()=>screen('onlineOptions'));
$('saveOnlineOptionsBtn')?.addEventListener('click',saveOptions);
$('startOnlineGameBtn')?.addEventListener('click',startOnline);
$('onlineMinusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.max(5,+e.textContent-1)});
$('onlinePlusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.min(20,+e.textContent+1)});
document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen||'home')));
});
