document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const ROLES={
'Joueur Gamer':['🎮','BONS','Aucun pouvoir.'],'Loup Gamer':['🐺','HACKERS','Choisit une victime chaque nuit.'],'Healer':['❤️‍🩹','BONS','Protège un joueur chaque nuit.'],'Stratège':['🧠','BONS','Pouvoir spécial.'],'Support':['🤝','BONS','Pouvoir spécial.'],'Analyste':['🔎','BONS','Pouvoir spécial.'],'Speedrunner':['⚡','BONS','Son vote peut compter double une fois.'],'Hacker':['💻','HACKERS','Pouvoir spécial.'],'Saboteur':['🧨','HACKERS','Pouvoir spécial.'],'Manipulateur':['🎭','SOLO','Gagne s’il est vivant à 3 joueurs.'],'Chaos':['🌀','SOLO','Gagne si ses deux cibles secrètes sont éliminées.'],'Opportuniste':['🎯','SOLO','Gagne avec le camp victorieux.'],'Boss Final':['👑','SOLO','Gagne s’il devient le dernier vivant.'],'Traître':['🗡️','BONS','Devient HACKER au tour 3.']};
let N={peer:null,host:false,room:'',pseudo:'',conns:{},players:[],settings:{max:8,roles:[]},game:null,ready:{}};
const go=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active')};
const status=t=>{if($('onlineStatus'))$('onlineStatus').textContent=t};
const send=(c,m)=>{if(c&&c.open)c.send(m)}; const broadcast=m=>Object.values(N.conns).forEach(c=>send(c,m));
const alive=()=>N.players.filter(p=>p.alive);
const hacker=p=>p&&(p.role==='Loup Gamer'||p.role==='Hacker'||p.role==='Saboteur'||(p.role==='Traître'&&N.game?.round>=3));
const team=p=>p.role==='Traître'&&N.game?.round>=3?'HACKERS':ROLES[p.role][1];
const publicPlayers=()=>N.players.map(p=>({pseudo:p.pseudo,alive:p.alive}));
function showLobby(){go('onlineLobby');$('roomCodeDisplay').textContent=N.room.replace(/^Loup64-/,'');$('lobbyPlayers').innerHTML=N.players.map((p,i)=>`<div class="player ${i===0?'active':''}"><strong>${esc(p.pseudo)}</strong><span>${i===0?'👑 Hôte':'🟢 Joueur'}</span></div>`).join('');$('startOnlineGameBtn').style.display=N.host?'block':'none';$('lobbyOptionsBtn').style.display=N.host?'block':'none';$('startOnlineGameBtn').disabled=N.players.length<5;}
function peer(id,ready){if(N.peer)try{N.peer.destroy()}catch(e){}N.peer=new Peer(id||undefined,{debug:0});N.peer.on('error',e=>{status('❌ '+(e.type==='peer-unavailable'?'Salon introuvable.':e.type==='unavailable-id'?'Code déjà utilisé.':'Connexion impossible.'));if(e.type==='peer-unavailable'||e.type==='unavailable-id')alert('❌ '+(e.type==='peer-unavailable'?'Salon introuvable.':'Ce code est déjà utilisé. Réessaie.'));});N.peer.on('open',id=>ready(id));N.peer.on('disconnected',()=>status('⚠️ Signalisation déconnectée.'))}
function create(){let p=$('createPseudo').value.trim();if(!p)return alert('⚠️ Entre ton pseudo.');N={...N,host:true,pseudo:p,players:[{pseudo:p,peerId:null,alive:true}],settings:{max:+$('onlinePlayerCount').textContent,roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)},game:null};status('Connexion…');peer('Loup64-'+Math.random().toString(36).slice(2,8).toUpperCase(),id=>{N.room=id;N.peer.on('connection',conn=>hostConnection(conn));showLobby();status('🟢 Salon prêt.');});}
function hostConnection(c){c.on('data',m=>hostMessage(c,m));c.on('close',()=>{let p=N.players.find(x=>x.peerId===c.peer);if(p){N.players=N.players.filter(x=>x!==p);delete N.conns[p.pseudo];showLobby();broadcast({type:'lobby',players:publicPlayers(),settings:N.settings});}})}
function hostMessage(c,m){if(!m)return;if(m.type==='join'){let p=String(m.pseudo||'').trim();if(N.game)return send(c,{type:'error',text:'La partie a déjà commencé.'});if(!p||N.players.some(x=>x.pseudo.toLowerCase()===p.toLowerCase()))return send(c,{type:'error',text:'Pseudo déjà utilisé.'});if(N.players.length>=N.settings.max)return send(c,{type:'error',text:'Salon complet.'});let pl={pseudo:p,peerId:c.peer,alive:true};N.players.push(pl);N.conns[p]=c;send(c,{type:'joined',room:N.room,players:publicPlayers(),settings:N.settings});broadcast({type:'lobby',players:publicPlayers(),settings:N.settings});showLobby();return}if(m.type==='ready')readyPlayer(findPseudo(c));if(m.type==='night')nightAction(findPseudo(c),m.action,m.value);if(m.type==='vote')vote(findPseudo(c),m.value,m.double)}
function findPseudo(c){return N.players.find(p=>p.peerId===c.peer)?.pseudo||''}
function join(){let p=$('joinPseudo').value.trim(),code=$('roomCode').value.trim().toUpperCase();if(!p||!code)return alert('⚠️ Entre ton pseudo et le code de la partie.');N.host=false;N.pseudo=p;status('Connexion au salon…');peer(undefined,()=>{let id=code.startsWith('LOUP64-')?code:'Loup64-'+code,c=N.peer.connect(id,{reliable:true,metadata:{pseudo:p}});N.conns.host=c;c.on('open',()=>send(c,{type:'join',pseudo:p}));c.on('data',clientMessage);c.on('close',()=>{alert('⚠️ La connexion avec l’hôte est perdue.');go('online')});});}
function clientMessage(m){if(m.type==='error'){alert('❌ '+m.text);return}if(m.type==='joined'||m.type==='lobby'){N.players=m.players.map(x=>({...x,peerId:null}));N.settings=m.settings;if(m.room)N.room=m.room;showLobby();return}if(m.type==='role'){N.game=m.game;N.game.myRole=m.role;renderOnline('role');return}if(m.type==='state'){N.game=m.game;renderOnline(m.mode);return}if(m.type==='prompt'){N.game=m.game;renderPrompt(m.prompt,m.options||[],m.doubleAllowed);return}if(m.type==='end'){renderEnd(m.winner,m.players)}}
function optionsSave(){if(!N.host)return;let max=+$('onlinePlayerCount').textContent;if(max<N.players.length)return alert('⚠️ Le maximum ne peut pas être inférieur aux joueurs présents.');N.settings.max=max;N.settings.roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);broadcast({type:'lobby',players:publicPlayers(),settings:N.settings});showLobby();}
function pool(){let r=['Loup Gamer','Healer',...N.settings.roles.filter(x=>x!=='Joueur Gamer')];while(r.length<N.players.length)r.push('Joueur Gamer');return r.slice(0,N.players.length)}
function start(){if(!N.host)return;if(N.players.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');let r=pool();for(let i=r.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}N.players.forEach((p,i)=>{p.role=r[i];p.alive=true;p.chaosTargets=[];p.speedUsed=false});let ch=N.players.find(p=>p.role==='Chaos');if(ch){let a=N.players.filter(x=>x!==ch).sort(()=>Math.random()-.5);ch.chaosTargets=a.slice(0,2).map(x=>x.pseudo)}N.game={round:1,phase:'reveal',actions:{},victim:null,protect:null,ready:{}};N.players.forEach(p=>{if(p.peerId)send(N.conns[p.pseudo],{type:'role',role:p.role,game:{round:1,phase:'reveal',players:publicPlayers(),myRole:p.role}})});broadcastState('reveal');renderOnline('hostReveal');}
function broadcastState(mode){let g={round:N.game.round,phase:N.game.phase,players:publicPlayers()};broadcast({type:'state',mode,game:g})}
function readyPlayer(p){if(!N.game||N.game.phase!=='reveal')return;N.game.ready[p]=true;if(Object.keys(N.game.ready).length===N.players.length)startNight()}
function startNight(){N.game.phase='night';N.game.actions={};N.game.victim=null;N.game.protect=null;broadcastState('night');nightNext()}
function nightNext(){let wolf=N.players.find(p=>p.alive&&p.role==='Loup Gamer'&&!N.game.actions[p.pseudo]);let healer=N.players.find(p=>p.alive&&p.role==='Healer'&&!N.game.actions[p.pseudo]);let actor=wolf||healer;if(actor){let prompt=wolf?'wolf':'heal',opts=wolf?N.players.filter(p=>p.alive&&p.role!=='Loup Gamer').map(p=>p.pseudo):alive().map(p=>p.pseudo);promptPlayer(actor,prompt,opts);return}resolveNight()}
function promptPlayer(p,prompt,options){let c=p.peerId?N.conns[p.pseudo]:null,game={round:N.game.round,phase:N.game.phase,players:publicPlayers()};if(c)send(c,{type:'prompt',prompt,options,game});else renderPrompt(prompt,options,false)}
function nightAction(p,a,v){if(!N.host||!p||N.game.phase!=='night'||N.game.actions[p])return;N.game.actions[p]={a,v};if(a==='wolf')N.game.victim=v;if(a==='heal')N.game.protect=v;nightNext()}
function resolveNight(){let v=N.players.find(p=>p.pseudo===N.game.victim);if(v&&v.pseudo!==N.game.protect)v.alive=false;N.game.phase='day';broadcastState('day');if(checkEnd())return;setTimeout(startVote,900)}
function startVote(){N.game.phase='vote';N.game.actions={};broadcastState('vote');alive().forEach(p=>{let opts=alive().filter(x=>x.pseudo!==p.pseudo).map(x=>x.pseudo);let c=p.peerId?N.conns[p.pseudo]:null;if(c)send(c,{type:'prompt',prompt:'vote',options:opts,doubleAllowed:p.role==='Speedrunner'&&!p.speedUsed,game:{round:N.game.round,phase:'vote',players:publicPlayers()}});else renderPrompt('vote',opts,p.role==='Speedrunner'&&!p.speedUsed)})}
function vote(p,target,double){if(!N.host||N.game.phase!=='vote'||!p||!p.alive||N.game.actions[p.pseudo])return;N.game.actions[p.pseudo]={a:'vote',v:target,double:!!double};if(double)p.speedUsed=true;if(Object.keys(N.game.actions).length===alive().length)resolveVote()}
function resolveVote(){let c={};alive().forEach(p=>{let a=N.game.actions[p.pseudo];if(a?.v)c[a.v]=(c[a.v]||0)+(a.double?2:1)});let max=Math.max(...Object.values(c),0),top=Object.keys(c).filter(x=>c[x]===max);if(top.length===1){let v=N.players.find(p=>p.pseudo===top[0]);if(v)v.alive=false}N.game.round++;if(checkEnd())return;startNight()}
function winner(){let a=alive(),m=a.find(p=>p.role==='Manipulateur'),ch=a.find(p=>p.role==='Chaos'),b=a.find(p=>p.role==='Boss Final');if(m&&a.length<=3)return'MANIPULATEUR';if(ch&&ch.chaosTargets.length===2&&ch.chaosTargets.every(n=>!N.players.find(p=>p.pseudo===n)?.alive))return'CHAOS';if(b&&a.length===1)return'BOSS FINAL';let h=a.filter(hacker).length;if(h===0)return'BONS';if(h>=a.length-h)return'HACKERS';return null}
function checkEnd(){let w=winner();if(!w)return false;let data=N.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.role}));broadcast({type:'end',winner:w,players:data});renderEnd(w,data);return true}
function renderOnline(mode){go('onlineGame');let g=N.game||{};$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':'☀️ Jour';$('onlineAlive').textContent=(g.players||publicPlayers()).filter(p=>p.alive).length;$('onlinePlayers').innerHTML=(g.players||publicPlayers()).map(p=>`<div class="player ${p.alive?'active':'dead'}"><strong>${esc(p.pseudo)}</strong><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'}</small></div>`).join('');if(mode==='role'){$('onlineAction').innerHTML=`<div class="night-card"><h3>🎭 Ton rôle</h3><div class="role-icon">${ROLES[g.myRole||N.game.myRole]?.[0]||'🎮'}</div><h2>${esc(g.myRole||N.game.myRole)}</h2><p>${esc(ROLES[g.myRole||N.game.myRole]?.[2]||'')}</p><button class="primary" id="readyOnline">✅ J’ai vu mon rôle</button></div>`;$('readyOnline').onclick=()=>{if(N.host)readyPlayer(N.pseudo);else send(N.conns.host,{type:'ready'});$('onlineAction').innerHTML='<div class="message">⏳ En attente des autres joueurs…</div>'};}else if(mode==='hostReveal')$('onlineAction').innerHTML='<div class="message">🎭 Les joueurs découvrent leur rôle sur leur propre appareil.</div>';else if(mode==='day')$('onlineAction').innerHTML='<div class="message">☀️ Nuit terminée. Prépare-toi à voter.</div>';else $('onlineAction').innerHTML='<div class="message">⏳ Attends ton action…</div>'}
function renderPrompt(prompt,opts,doubleAllowed){go('onlineGame');$('onlineAction').innerHTML=`<div class="night-card"><h3>${prompt==='wolf'?'🐺 Choisis la victime':prompt==='heal'?'❤️‍🩹 Choisis qui protéger':'🗳️ Vote'}</h3><select id="onlineChoice"><option value="">Choisir…</option>${opts.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>${prompt==='vote'&&doubleAllowed?'<label style="display:block;margin:12px 0"><input id="doubleVote" type="checkbox"> ⚡ Utiliser mon double vote</label>':''}<button class="primary" id="onlineConfirm">✅ Valider</button></div>`;$('onlineConfirm').onclick=()=>{let v=$('onlineChoice').value;if(!v)return alert('⚠️ Choisis un joueur.');let dbl=$('doubleVote')?.checked||false;if(N.host){if(prompt==='vote')vote(N.pseudo,v,dbl);else nightAction(N.pseudo,prompt,v)}else if(prompt==='vote')send(N.conns.host,{type:'vote',value:v,double:dbl});else send(N.conns.host,{type:'night',action:prompt,value:v});$('onlineAction').innerHTML='<div class="message">⏳ Action enregistrée…</div>'}}
function renderEnd(w,players){go('onlineEnd');let m={BONS:['🛡️','Victoire des BONS !'],HACKERS:['🐺','Victoire des HACKERS !'],MANIPULATEUR:['🎭','Victoire du MANIPULATEUR !'],CHAOS:['🌀','Victoire du CHAOS !'],'BOSS FINAL':['👑','Victoire du BOSS FINAL !']}[w]||['🏆','Victoire !'];$('onlineWinnerIcon').textContent=m[0];$('onlineWinnerTitle').textContent=m[1];$('onlineFinalPlayers').innerHTML=players.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.pseudo)}</strong><span>${ROLES[p.role]?.[0]||'🎮'} ${esc(p.role)}</span></div>`).join('')}
$('onlineBtn')?.addEventListener('click',()=>go('online'));$('createOnlineBtn')?.addEventListener('click',()=>go('onlineCreate'));$('joinOnlineBtn')?.addEventListener('click',()=>go('onlineJoin'));$('createRoomBtn')?.addEventListener('click',create);$('joinRoomBtn')?.addEventListener('click',join);$('lobbyOptionsBtn')?.addEventListener('click',()=>go('onlineOptions'));$('saveOnlineOptionsBtn')?.addEventListener('click',optionsSave);$('startOnlineGameBtn')?.addEventListener('click',start);$('onlineMinusPlayers')?.addEventListener('click',()=>{$('onlinePlayerCount').textContent=Math.max(5,+$('onlinePlayerCount').textContent-1)});$('onlinePlusPlayers')?.addEventListener('click',()=>{$('onlinePlayerCount').textContent=Math.min(20,+$('onlinePlayerCount').textContent+1)});document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen||'home')));
});