document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const ROLES={'Joueur Gamer':{icon:'🎮',team:'BONS',desc:'Aucun pouvoir.'},'Loup Gamer':{icon:'🐺',team:'HACKERS',desc:'Choisit une victime chaque nuit.'},'Healer':{icon:'❤️‍🩹',team:'BONS',desc:'Protège un joueur chaque nuit.'},'Stratège':{icon:'🧠',team:'BONS',desc:'Une fois, peut annuler une élimination par vote.'},'Support':{icon:'🤝',team:'BONS',desc:'Une fois, protège un joueur.'},'Analyste':{icon:'🔎',team:'BONS',desc:'Une fois, découvre le camp d’un joueur.'},'Speedrunner':{icon:'⚡',team:'BONS',desc:'Une fois, son vote compte double.'},'Hacker':{icon:'💻',team:'HACKERS',desc:'Une fois, bloque le pouvoir d’un joueur.'},'Saboteur':{icon:'🧨',team:'HACKERS',desc:'Une fois, déclenche un faux événement.'},'Manipulateur':{icon:'🎭',team:'SOLO',desc:'Gagne s’il est vivant à 3 joueurs.'},'Chaos':{icon:'🌀',team:'SOLO',desc:'Gagne si ses deux cibles secrètes sont éliminées.'},'Opportuniste':{icon:'🎯',team:'SOLO',desc:'Peut changer son vote deux fois et gagne avec le camp victorieux.'},'Boss Final':{icon:'👑',team:'SOLO',desc:'Gagne s’il devient le dernier joueur vivant.'},'Traître':{icon:'🗡️',team:'BONS',desc:'Devient HACKER à partir du tour 3.'}};
let net={peer:null,host:false,room:'',pseudo:'',conns:{},players:[],settings:{max:8,roles:[]},game:null};
const screen=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')};
const say=t=>{if(window.speechSynthesis){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.9;speechSynthesis.speak(u)}};
function onlineStatus(t){const e=$('onlineStatus');if(e)e.textContent=t}
function send(conn,msg){if(conn&&conn.open)conn.send(msg)}
function broadcast(msg){Object.values(net.conns).forEach(c=>send(c,msg))}
function publicPlayers(){return net.players.map(p=>({pseudo:p.pseudo,alive:p.alive}))}
function lobbyRender(){if($('roomCodeDisplay'))$('roomCodeDisplay').textContent=net.room.replace(/^Loup64-/,'');if($('lobbyPlayers'))$('lobbyPlayers').innerHTML=net.players.map((p,i)=>`<div class="player ${i===0?'active':''}"><strong>${esc(p.pseudo)}</strong><span>${i===0?'👑 Hôte':'🟢 Joueur'}</span></div>`).join('');if($('startOnlineGameBtn'))$('startOnlineGameBtn').disabled=net.players.length<5}
function connectPeer(id,onOpen){if(net.peer)try{net.peer.destroy()}catch(e){}net.peer=new Peer(id||undefined,{debug:0});net.peer.on('error',e=>{onlineStatus('❌ '+(e.type==='peer-unavailable'?'Salon introuvable.':e.type==='unavailable-id'?'Code déjà utilisé, réessaie.':'Connexion impossible.'));alert('❌ '+(e.type==='peer-unavailable'?'Salon introuvable.':e.message||'Connexion impossible.'))});net.peer.on('disconnected',()=>onlineStatus('⚠️ Connexion au serveur de signalisation perdue.'));net.peer.on('open',peerId=>{if(net.host)net.peer.on('connection',attachHostConnection);if(onOpen)onOpen(peerId)})}
function createRoom(){const pseudo=$('createPseudo').value.trim();if(!pseudo)return alert('⚠️ Entre ton pseudo.');net.host=true;net.pseudo=pseudo;net.players=[{peerId:null,pseudo,alive:true}];net.settings={max:+($('onlinePlayerCount')?.textContent||8),roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)};onlineStatus('Connexion…');const id='Loup64-'+Math.random().toString(36).slice(2,8).toUpperCase();connectPeer(id,actual=>{net.room=actual;lobbyRender();screen('onlineLobby');onlineStatus('🟢 Salon créé.');say('Salon créé.')})}
function attachHostConnection(conn){const pid=conn.peer;conn.on('data',msg=>hostMessage(conn,msg));conn.on('close',()=>{const p=net.players.find(x=>x.peerId===pid);if(p){net.players=net.players.filter(x=>x.peerId!==pid);delete net.conns[p.pseudo];lobbyRender();broadcast({type:'lobby',players:publicPlayers(),settings:net.settings})}})}
function hostMessage(conn,msg){if(!msg||!net.host)return;if(msg.type==='join'){if(net.game)return send(conn,{type:'error',text:'La partie a déjà commencé.'});const pseudo=String(msg.pseudo||'').trim();if(!pseudo||net.players.some(p=>p.pseudo.toLowerCase()===pseudo.toLowerCase()))return send(conn,{type:'error',text:'Pseudo déjà utilisé ou invalide.'});if(net.players.length>=net.settings.max)return send(conn,{type:'error',text:'Le salon est complet.'});const p={peerId:conn.peer,pseudo,alive:true};net.players.push(p);net.conns[pseudo]=conn;send(conn,{type:'joined',room:net.room,host:true,players:publicPlayers(),settings:net.settings});broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});lobbyRender();return}if(msg.type==='action')onlineAction(pseudoFromConn(conn),msg.action,msg.value);if(msg.type==='ready')onlineReady(pseudoFromConn(conn))}
function pseudoFromConn(conn){return net.players.find(p=>p.peerId===conn.peer)?.pseudo||''}
function joinRoom(){const pseudo=$('joinPseudo').value.trim(),code=$('roomCode').value.trim().toUpperCase();if(!pseudo||!code)return alert('⚠️ Entre ton pseudo et le code de la partie.');net.host=false;net.pseudo=pseudo;onlineStatus('Connexion au salon…');connectPeer(undefined,()=>{const conn=net.peer.connect(code.startsWith('LOUP64-')?code:'Loup64-'+code,{reliable:true,metadata:{pseudo}});net.conns.host=conn;conn.on('open',()=>send(conn,{type:'join',pseudo}));conn.on('data',clientMessage);conn.on('close',()=>{onlineStatus('⚠️ L’hôte a fermé la connexion.');alert('⚠️ La connexion avec l’hôte est perdue.');screen('online')});conn.on('error',()=>onlineStatus('❌ Erreur de connexion.'))})}
function clientMessage(msg){if(msg.type==='error'){onlineStatus('❌ '+msg.text);alert('❌ '+msg.text);return}if(msg.type==='joined'){net.room=msg.room;net.players=msg.players.map(p=>({...p,peerId:null}));net.settings=msg.settings;renderOnlineLobby(false);return}if(msg.type==='lobby'){net.players=msg.players;net.settings=msg.settings;renderOnlineLobby(false);return}if(msg.type==='privateRole'){net.game=net.game||{};net.game.role=msg.role;net.game.team=msg.team;renderOnlineGame('role');return}if(msg.type==='game'){const old=net.game||{};net.game={...msg.game,role:old.role,team:old.team};renderOnlineGame(msg.mode||'public');return}if(msg.type==='actionPrompt'){renderPrompt(msg.prompt,msg.options||[],msg.extra||{});return}if(msg.type==='notice'){onlineStatus(msg.text);if(msg.speak)say(msg.text);return}if(msg.type==='end'){renderOnlineEnd(msg.winner,msg.players);return}}
function renderOnlineLobby(host){lobbyRender();if($('lobbyOptionsBtn'))$('lobbyOptionsBtn').style.display=host?'block':'none';if($('startOnlineGameBtn'))$('startOnlineGameBtn').style.display=host?'block':'none';screen('onlineLobby')}
function saveOptions(){if(!net.host)return;net.settings.max=+($('onlinePlayerCount').textContent||8);net.settings.roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);if(net.players.length>net.settings.max)return alert('⚠️ Le nouveau maximum est inférieur au nombre de joueurs déjà présents.');if(net.settings.roles.length>net.settings.max-2)return alert('⚠️ Trop de rôles spéciaux pour ce nombre de joueurs.');broadcast({type:'lobby',players:publicPlayers(),settings:net.settings});renderOnlineLobby(true)}
function rolePool(){let r=['Loup Gamer','Healer'];net.settings.roles.forEach(x=>{if(x!=='Joueur Gamer')r.push(x)});while(r.length<net.players.length)r.push('Joueur Gamer');return r.slice(0,net.players.length)}
function startOnline(){if(!net.host)return;if(net.players.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');if(net.settings.roles.length>net.players.length-2)return alert('⚠️ Trop de rôles spéciaux. Réduis-les dans les options.');let names=rolePool();for(let i=names.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[names[i],names[j]]=[names[j],names[i]]}net.players.forEach((p,i)=>{p.alive=true;p.roleName=names[i];p.role=ROLES[names[i]];p.voted=null;p.doubleUsed=false;p.powerUsed=false;p.blocked=false;p.protected=false;p.chaosTargets=[]});const chaos=net.players.find(p=>p.roleName==='Chaos');if(chaos){let o=net.players.filter(p=>p!==chaos).sort(()=>Math.random()-.5);chaos.chaosTargets=o.slice(0,2).map(p=>p.pseudo)}net.game={round:1,phase:'reveal',nightVictim:null,nightProtect:null,supportProtect:null,blocked:null,actions:{},ready:{}};net.players.forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'privateRole',role:p.roleName,team:dynamicTeam(p)})});broadcastGame('reveal');renderOnlineGame('reveal')}
function dynamicTeam(p){return p.roleName==='Traître'&&net.game&&net.game.round>=3?'HACKERS':p.role.team}
function broadcastGame(mode){const pub={round:net.game.round,phase:net.game.phase,players:publicPlayers(),victim:net.game.nightVictim,protected:net.game.nightProtect,blocked:net.game.blocked};broadcast({type:'game',game:pub,mode})}
function renderOnlineGame(mode){screen('onlineGame');const g=net.game||{};$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':'☀️ Jour';$('onlineAlive').textContent=(g.players||publicPlayers()).filter(p=>p.alive).length;let list=g.players||publicPlayers();$('onlinePlayers').innerHTML=list.map(p=>`<div class="player ${p.alive?'active':'dead'}"><strong>${esc(p.pseudo)}</strong><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'}</small></div>`).join('');if(mode==='role'||mode==='reveal'){const myRole=g.role||net.players.find(p=>p.pseudo===net.pseudo)?.roleName||'Joueur Gamer';$('onlineAction').innerHTML=`<div class="night-card"><h3>🎭 Ton rôle</h3><div class="role-icon">${ROLES[myRole]?.icon||'🎮'}</div><h3>${esc(myRole)}</h3><p>${esc(ROLES[myRole]?.desc||'')}</p><button class="primary" id="onlineReadyBtn">✅ J’ai vu mon rôle</button></div>`;$('onlineReadyBtn').onclick=()=>{if(net.host)onlineReady(net.pseudo);else send(net.conns.host,{type:'ready'});$('onlineAction').innerHTML='<div class="message">⏳ En attente des autres joueurs…</div>'};return}if(net.host)hostNextUI();else $('onlineAction').innerHTML='<div class="message">⏳ Attends l’action du jeu…</div>'}
function onlineReady(pseudo){if(!net.host||!net.game)return;net.game.ready[pseudo]=true;if(Object.keys(net.game.ready).length===net.players.length)startNight();else broadcast({type:'notice',text:`${pseudo} est prêt.`})}
function startNight(){net.game.phase='night';net.game.actions={};net.game.nightVictim=null;net.game.nightProtect=null;net.game.supportProtect=null;net.game.blocked=null;net.game.ready={};broadcastGame('night');hostNextNight()}
function hostNextNight(){if(!net.host)return;let roles=['Hacker','Saboteur','Analyste','Support','Loup Gamer','Traître','Healer'];let pending=roles.find(r=>net.players.find(x=>x.alive&&x.roleName===r&&!net.game.actions[x.pseudo]));if(pending){let p=net.players.find(x=>x.alive&&x.roleName===pending&&!net.game.actions[x.pseudo]);if(['Loup Gamer','Traître'].includes(pending)){promptHost(p,'wolf',net.players.filter(x=>x.alive&&x.roleName!=='Loup Gamer'&&x.roleName!=='Healer').map(x=>x.pseudo));return}if(pending==='Healer'){promptHost(p,'protect',net.players.filter(x=>x.alive).map(x=>x.pseudo));return}if(pending==='Hacker'){promptHost(p,'block',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo));return}if(pending==='Analyste'){promptHost(p,'analyse',net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo));return}if(pending==='Support'){promptHost(p,'support',net.players.filter(x=>x.alive).map(x=>x.pseudo));return}if(pending==='Saboteur'){promptHost(p,'sabotage',[]);return}}resolveNight()}
function promptHost(p,prompt,options){const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt,options});else renderPrompt(prompt,options)}
function renderPrompt(prompt,options){const labels={wolf:'🐺 Choisis la victime',protect:'❤️‍🩹 Choisis qui protéger',block:'💻 Choisis le pouvoir à bloquer',analyse:'🔎 Choisis qui analyser',support:'🤝 Choisis qui protéger',sabotage:'🧨 Déclenche ton faux événement',strategy:'🧠 Un joueur va être éliminé, utiliser ton pouvoir ?',vote:'🗳️ Choisis qui éliminer'};let html=`<div class="night-card"><h3>${labels[prompt]||'Action'}</h3>`;if(options.length)html+=`<select id="onlineChoice"><option value="">Choisir…</option>${options.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select>`;html+=`<button class="primary" id="onlineActionBtn">${prompt==='sabotage'?'🧨 Déclencher':'✅ Valider'}</button></div>`;$('onlineAction').innerHTML=html;$('onlineActionBtn').onclick=()=>{let v=$('onlineChoice')?.value||true;if(options.length&&!v)return alert('⚠️ Choisis un joueur.');if(net.host)onlineAction(net.pseudo,{prompt,value:v});else send(net.conns.host,{type:'action',action:{prompt,value:v}})}}
function onlineAction(pseudo,action,value){if(!net.host||!net.game)return;let p=net.players.find(x=>x.pseudo===pseudo);if(!p||!p.alive)return;let a=action&&action.prompt?action:{prompt:action,value};if(a.prompt==='strategy'){if(net.game.phase!=='vote'||net.game.actions[pseudo])return;net.game.actions[pseudo]=a;let victim=net.players.find(x=>x.pseudo===net.game.pendingVoteVictim);if(victim&&a.value!=='Annuler l’élimination')victim.alive=false;net.game.pendingVoteVictim=null;finishVoteRound();return}if(a.prompt==='vote'){onlineVote(pseudo,a.value);return}if(net.game.phase!=='night'||net.game.actions[pseudo])return;net.game.actions[pseudo]=a;let target=a.value;if(a.prompt==='wolf')net.game.nightVictim=target;if(a.prompt==='protect')net.game.nightProtect=target;if(a.prompt==='support')net.game.supportProtect=target;if(a.prompt==='block')net.game.blocked=target;if(a.prompt==='analyse'){let t=net.players.find(x=>x.pseudo===target);const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'notice',text:`🔎 ${target} est ${isHacker(t)?'HACKER':'BON'}.`})}if(a.prompt==='sabotage')broadcast({type:'notice',text:'🚨 Une fausse alerte a été déclenchée cette nuit.',speak:false});broadcastGame('night');hostNextNight()}
function isHacker(p){return p&&(p.roleName==='Loup Gamer'||p.roleName==='Hacker'||p.roleName==='Saboteur'||(p.roleName==='Traître'&&net.game.round>=3))}
function resolveNight(){let v=net.players.find(p=>p.pseudo===net.game.nightVictim);if(v&&v.pseudo!==net.game.nightProtect&&v.pseudo!==net.game.supportProtect&&net.game.blocked!==v.pseudo)v.alive=false;net.game.phase='day';broadcastGame('day');if(checkOnlineEnd())return;setTimeout(startVote,700)}
function startVote(){net.game.phase='vote';net.game.actions={};broadcastGame('vote');net.players.filter(p=>p.alive).forEach(p=>{const c=p.peerId?net.conns[p.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt:'vote',options:net.players.filter(x=>x.alive&&x.pseudo!==p.pseudo).map(x=>x.pseudo)})});if(net.players.find(p=>p.alive&&!p.peerId))renderPrompt('vote',net.players.filter(x=>x.alive&&x.pseudo!==net.pseudo).map(x=>x.pseudo))}
function resolveVote(){let counts={};net.players.filter(p=>p.alive).forEach(p=>{let a=net.game.actions[p.pseudo];if(a?.prompt==='vote'&&a.value)counts[a.value]=(counts[a.value]||0)+(p.roleName==='Speedrunner'&&!p.doubleUsed&&a.double?2:1)});let max=Math.max(0,...Object.values(counts)),tops=Object.keys(counts).filter(k=>counts[k]===max);if(tops.length===1){let victim=net.players.find(p=>p.pseudo===tops[0]),strat=net.players.find(p=>p.alive&&p.roleName==='Stratège'&&!p.powerUsed);if(strat){strat.powerUsed=true;net.game.pendingVoteVictim=victim.pseudo;const c=strat.peerId?net.conns[strat.pseudo]:null;if(c)send(c,{type:'actionPrompt',prompt:'strategy',options:['Annuler l’élimination','Ne rien faire']});else renderPrompt('strategy',['Annuler l’élimination','Ne rien faire']);return}victim.alive=false}finishVoteRound()}
function finishVoteRound(){net.game.round++;if(checkOnlineEnd())return;startNight()}
function onlineVote(pseudo,value){if(!net.host||!net.game||net.game.phase!=='vote')return;let p=net.players.find(x=>x.pseudo===pseudo);if(!p||!p.alive||net.game.actions[pseudo])return;net.game.actions[pseudo]={prompt:'vote',value};broadcastGame('vote');if(net.players.filter(x=>x.alive).every(x=>net.game.actions[x.pseudo]))resolveVote()}
function checkOnlineEnd(){let a=net.players.filter(p=>p.alive),m=a.find(p=>p.roleName==='Manipulateur'),c=a.find(p=>p.roleName==='Chaos'),b=a.find(p=>p.roleName==='Boss Final'),winner=null;if(m&&a.length<=3)winner='MANIPULATEUR';else if(c&&c.chaosTargets?.length===2&&c.chaosTargets.every(n=>!net.players.find(p=>p.pseudo===n)?.alive))winner='CHAOS';else if(b&&a.length===1)winner='BOSS FINAL';else{let h=a.filter(isHacker).length;if(h===0)winner='BONS';else if(h>=a.length-h)winner='HACKERS'}if(!winner)return false;broadcast({type:'end',winner,players:net.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.roleName}))});renderOnlineEnd(winner,net.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.roleName})));return true}
function hostNextUI(){if(net.game.phase==='reveal')renderOnlineGame('reveal');else renderOnlineGame('public')}
function renderOnlineEnd(w,players){screen('onlineEnd');const map={BONS:['🛡️','Victoire des BONS !'],HACKERS:['🐺','Victoire des HACKERS !'],MANIPULATEUR:['🎭','Victoire du MANIPULATEUR !'],CHAOS:['🌀','Victoire du CHAOS !'],'BOSS FINAL':['👑','Victoire du BOSS FINAL !']};let x=map[w]||['🏆','Victoire !'];$('onlineWinnerIcon').textContent=x[0];$('onlineWinnerTitle').textContent=x[1];$('onlineFinalPlayers').innerHTML=players.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.pseudo)}</strong><span>${ROLES[p.role]?.icon||'🎮'} ${esc(p.role)}</span></div>`).join('')}
$('onlineBtn')?.addEventListener('click',()=>screen('online'));$('createOnlineBtn')?.addEventListener('click',()=>screen('onlineCreate'));$('joinOnlineBtn')?.addEventListener('click',()=>screen('onlineJoin'));$('createRoomBtn')?.addEventListener('click',createRoom);$('joinRoomBtn')?.addEventListener('click',joinRoom);$('lobbyOptionsBtn')?.addEventListener('click',()=>screen('onlineOptions'));$('saveOnlineOptionsBtn')?.addEventListener('click',saveOptions);$('startOnlineGameBtn')?.addEventListener('click',startOnline);$('onlineMinusPlayers')?.addEventListener('click',()=>{let e=$('onlinePlayerCount');e.textContent=Math.max(5,+e.textContent-1)});$('onlinePlusPlayers')?.addEventListener('click',()=>{let e=$('onlinePlayerCount');e.textContent=Math.min(20,+e.textContent+1)});document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen||'home')));
});