document.addEventListener('DOMContentLoaded',()=>{
const ROLES={
'Joueur Gamer':{icon:'🎮',team:'BONS',desc:'Aucun pouvoir. Gagne avec les BONS.'},
'Loup Gamer':{icon:'🐺',team:'HACKERS',desc:'Choisit une victime chaque nuit.'},
'Healer':{icon:'❤️‍🩹',team:'BONS',desc:'Protège un joueur pendant la nuit.'},
'Stratège':{icon:'🧠',team:'BONS',desc:'Une fois, peut annuler une élimination par vote.'},
'Support':{icon:'🤝',team:'BONS',desc:'Une fois, protège un joueur d’une élimination de jour ou de nuit. Peut se protéger.'},
'Analyste':{icon:'🔎',team:'BONS',desc:'Une fois, découvre si un joueur est BON ou HACKER.'},
'Speedrunner':{icon:'⚡',team:'BONS',desc:'Une fois par partie, son vote compte double.'},
'Hacker':{icon:'💻',team:'HACKERS',desc:'Une fois, bloque le pouvoir d’un joueur pendant la nuit.'},
'Saboteur':{icon:'🧨',team:'HACKERS',desc:'Une fois, déclenche un faux événement pour semer le doute.'},
'Manipulateur':{icon:'🎭',team:'SOLO',desc:'Gagne s’il est vivant lorsqu’il reste 3 joueurs.'},
'Chaos':{icon:'🌀',team:'SOLO',desc:'Choisit secrètement 2 joueurs. Gagne si les deux sont éliminés.'},
'Opportuniste':{icon:'🎯',team:'SOLO',desc:'Peut changer son vote 2 fois et gagne avec le camp victorieux.'},
'Boss Final':{icon:'👑',team:'SOLO',desc:'Gagne s’il devient le dernier joueur vivant.'},
'Traître':{icon:'🗡️',team:'BONS',desc:'Commence BON puis rejoint les HACKERS à partir du tour 3.'}
};
let state={players:[],index:0,phase:'reveal',round:1,nightStep:0,nightVictim:null,protected:null,supportProtected:null,voteIndex:0,votes:{},blocked:null,chaosTargets:[],uses:{},voteChanges:0};
let voiceEnabled=true,$=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')}
function speak(t){if(!voiceEnabled||!window.speechSynthesis)return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.88;u.pitch=.85;window.speechSynthesis.speak(u)}
function voice(){return `<button class="secondary" id="voiceBtn">🔊 Voix : ${voiceEnabled?'ON':'OFF'}</button>`}
function bindVoice(){let b=$('voiceBtn');if(b)b.onclick=()=>{voiceEnabled=!voiceEnabled;if(!voiceEnabled&&window.speechSynthesis)window.speechSynthesis.cancel();b.textContent=`🔊 Voix : ${voiceEnabled?'ON':'OFF'}`}}
function renderNames(){let n=+$('playerCount').textContent||8,box=$('namesBox');box.innerHTML='';for(let i=1;i<=n;i++)box.insertAdjacentHTML('beforeend',`<div class="name-row"><label>👤 Joueur ${i}</label><input id="player-${i}" class="name-input" maxlength="20" placeholder="Entre ton pseudo" value="Joueur ${i}"></div>`)}
function updateRoleCount(){let n=document.querySelectorAll('.special-role:checked').length,e=$('roleCount');if(e)e.textContent=`${n} rôle${n>1?'s':''} spécial${n>1?'s':''} activé${n>1?'s':''}`}
function setup(){renderNames();document.querySelectorAll('.special-role').forEach(x=>x.checked=false);updateRoleCount();screen('setup')}
function changePlayers(d){let e=$('playerCount');e.textContent=Math.max(5,Math.min(20,(+e.textContent||8)+d));renderNames()}
function launch(){
 let names=[...document.querySelectorAll('.name-input')].map(i=>i.value.trim());
 if(names.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');
 if(names.some(n=>!n))return alert('⚠️ Tous les joueurs doivent avoir un pseudo.');
 if(new Set(names.map(n=>n.toLowerCase())).size!==names.length)return alert('⚠️ Les pseudos doivent être différents.');
 let selected=[...document.querySelectorAll('.special-role:checked')].map(x=>x.value);
 if(selected.length>names.length-2)return alert(`⚠️ Trop de rôles spéciaux. Avec ${names.length} joueurs, choisis au maximum ${names.length-2}.`);
 let roleNames=['Loup Gamer','Healer'];
 if(selected.includes('Hacker'))roleNames.push('Hacker');
 selected.filter(r=>r!=='Hacker').forEach(r=>roleNames.push(r));
 while(roleNames.length<names.length)roleNames.push('Joueur Gamer');
 roleNames=roleNames.slice(0,names.length);
 for(let i=roleNames.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[roleNames[i],roleNames[j]]=[roleNames[j],roleNames[i]]}
 state={players:names.map((name,i)=>({name,role:ROLES[roleNames[i]],roleName:roleNames[i],alive:true}),),index:0,phase:'reveal',round:1,nightStep:0,nightVictim:null,protected:null,supportProtected:null,voteIndex:0,votes:{},blocked:null,chaosTargets:[],uses:{},voteChanges:0};
 state.players.forEach(p=>{state.uses[p.name]={power:false,double:false,block:false,sabotage:false,support:false,strategy:false,chaos:false}});
 let chaos=state.players.find(p=>p.roleName==='Chaos');
 if(chaos){let others=state.players.filter(p=>p.name!==chaos.name);for(let i=others.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[others[i],others[j]]=[others[j],others[i]]}state.chaosTargets=others.slice(0,2).map(p=>p.name)}
 showReveal()
}
function showReveal(){let p=state.players[state.index];if(!p)return;$('revealPlayer').textContent=p.name;$('roleCard').classList.add('hidden');$('showRoleBtn').classList.remove('hidden');screen('reveal')}
function reveal(){let p=state.players[state.index];if(!p)return;$('roleIcon').textContent=p.role.icon;$('roleName').textContent=p.roleName;$('roleTeam').textContent=dynamicTeam(p);$('roleDescription').textContent=p.role.desc;$('roleCard').classList.remove('hidden');$('showRoleBtn').classList.add('hidden');speak(`${p.name}, découvre ton rôle.`)}
function nextReveal(){if(++state.index>=state.players.length)startGame();else showReveal()}
function alive(){return state.players.filter(p=>p.alive)}
function isHacker(p){return p&&p.alive&&(p.roleName==='Loup Gamer'||p.roleName==='Hacker'||p.roleName==='Saboteur'||(p.roleName==='Traître'&&state.round>=3))}
function dynamicTeam(p){if(p.roleName==='Traître'&&state.round>=3)return'HACKERS';if(p.role.team==='SOLO')return'SOLO';return p.role.team}
function update(t){$('roundLabel').textContent=`TOUR ${state.round}`;$('phaseTitle').textContent=t;$('aliveCount').textContent=alive().length}
function render(active=[]){let a=new Set(active);$('playersList').innerHTML=state.players.map(p=>`<div class="player ${!p.alive?'dead':!a.size?'':a.has(p.name)?'active':'inactive'}"><strong>${esc(p.name)}</strong><br><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'} · ${esc(dynamicTeam(p))}</small></div>`).join('')}
function soloWinner(){let a=alive();let m=a.find(p=>p.roleName==='Manipulateur');if(m&&a.length<=3)return'MANIPULATEUR';let c=a.find(p=>p.roleName==='Chaos');if(c&&state.chaosTargets.length===2&&state.chaosTargets.every(n=>!state.players.find(p=>p.name===n)?.alive))return'CHAOS';let b=a.find(p=>p.roleName==='Boss Final');if(b&&a.length===1)return'BOSS FINAL';return null}
function winner(){let solo=soloWinner();if(solo)return solo;let a=alive(),h=a.filter(isHacker).length,b=a.filter(p=>!isHacker(p)&&p.roleName!=='Manipulateur'&&p.roleName!=='Chaos'&&p.roleName!=='Boss Final').length;if(h===0)return'BONS';if(h>=b)return'HACKERS';return null}
function checkEnd(){let w=winner();if(!w)return false;finish(w);return true}
function finish(w){state.phase='end';let title='Victoire !',icon='🏆',msg='';if(w==='HACKERS'){icon='🐺';title='Victoire des HACKERS !';msg='Les Hackers ont pris le dessus.'}else if(w==='BONS'){icon='🛡️';title='Victoire des BONS !';msg='Tous les Hackers ont été éliminés.'}else if(w==='MANIPULATEUR'){icon='🎭';title='Victoire du MANIPULATEUR !';msg='Le Manipulateur a survécu jusqu’à 3 joueurs.'}else if(w==='CHAOS'){icon='🌀';title='Victoire du CHAOS !';msg='Ses deux cibles ont été éliminées.'}else if(w==='BOSS FINAL'){icon='👑';title='Victoire du BOSS FINAL !';msg='Il est le dernier joueur vivant.'}$('winnerIcon').textContent=icon;$('winnerTitle').textContent=title;$('winnerMessage').textContent=msg;let op=state.players.find(p=>p.roleName==='Opportuniste');if(op&&op.alive&&['BONS','HACKERS'].includes(w))$('winnerMessage').textContent+=` L’Opportuniste gagne aussi avec les ${w}.`;$('finalPlayers').innerHTML=state.players.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.name)}</strong><span><b>${p.role.icon} ${esc(p.roleName)}</b><br><small>${esc(dynamicTeam(p))}</small></span></div>`).join('');screen('end');speak(msg)}
function startGame(){state.phase='night';state.round=1;state.nightStep=0;state.nightVictim=null;state.protected=null;state.supportProtected=null;state.votes={};screen('game');update('🌙 Nuit 1');render();nightIntro()}
function nightIntro(){if(checkEnd())return;$('gameMessage').textContent=`La nuit ${state.round} commence.`;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🌙 La nuit tombe...</h3><p>Les rôles spéciaux vont jouer à tour de rôle.</p><button class="primary" id="startNightBtn">🌙 Commencer la nuit</button></div>`;bindVoice();speak('La nuit tombe sur le village.');$('startNightBtn').onclick=nightStep}
function opts(exclude=''){return alive().filter(p=>p.name!==exclude).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')}
function blocked(name){return state.blocked===name}
function nightStep(){
 let hacker=alive().find(p=>p.roleName==='Hacker'&&!state.uses[p.name].block);
 let sab=alive().find(p=>p.roleName==='Saboteur'&&!state.uses[p.name].sabotage);
 let analyst=alive().find(p=>p.roleName==='Analyste'&&!state.uses[p.name].power);
 let support=alive().find(p=>p.roleName==='Support'&&!state.uses[p.name].support);
 let wolf=alive().find(p=>p.roleName==='Loup Gamer');
 let traitor=alive().find(p=>p.roleName==='Traître'&&state.round>=3);
 let healer=alive().find(p=>p.roleName==='Healer');
 if(state.nightStep===0&&hacker){state.nightStep=1;hackerTurn(hacker);return}
 if(state.nightStep<=1&&sab){state.nightStep=2;saboteurTurn(sab);return}
 if(state.nightStep<=2&&analyst){state.nightStep=3;analystTurn(analyst);return}
 if(state.nightStep<=3&&support){state.nightStep=4;supportTurn(support);return}
 if(state.nightStep<=4&&(wolf||traitor)){state.nightStep=5;wolfTurn(wolf,traitor);return}
 if(state.nightStep<=5&&healer){state.nightStep=6;healTurn(healer);return}
 finishNight()
}
function hackerTurn(p){$('gameMessage').textContent='💻 Le Hacker se réveille.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>💻 Hacker</h3><p>Choisis un joueur dont le pouvoir sera bloqué cette nuit.</p><select id="blockTarget"><option value="">Choisir un joueur</option>${opts(p.name)}</select><button class="primary" id="blockConfirm">💻 Bloquer</button></div>`;bindVoice();speak('Le Hacker se réveille.');$('blockConfirm').onclick=()=>{let t=$('blockTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.blocked=t;state.uses[p.name].block=true;nightStep()}}
function saboteurTurn(p){$('gameMessage').textContent='🧨 Le Saboteur agit.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🧨 Saboteur</h3><p>Tu peux déclencher ton faux événement une seule fois.</p><button class="primary" id="sabotageConfirm">🧨 Déclencher le faux événement</button></div>`;bindVoice();speak('Le Saboteur prépare un faux événement.');$('sabotageConfirm').onclick=()=>{state.uses[p.name].sabotage=true;$('gameMessage').textContent='🚨 FAUSSE ALERTE';$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🚨 Événement suspect !</h3><p>Une alerte étrange vient d’être détectée… mais rien ne permet de savoir qui ment.</p><button class="primary" id="fakeContinue">Continuer</button></div>`;bindVoice();$('fakeContinue').onclick=nightStep}}
function analystTurn(p){if(blocked(p.name)){state.nightStep++;return nightStep()}$('gameMessage').textContent='🔎 L’Analyste se réveille.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🔎 Analyste</h3><p>Choisis un joueur pour connaître son camp.</p><select id="analysisTarget"><option value="">Choisir un joueur</option>${opts(p.name)}</select><button class="primary" id="analysisConfirm">🔎 Analyser</button></div>`;bindVoice();speak('L’Analyste se réveille.');$('analysisConfirm').onclick=()=>{let t=$('analysisTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');let target=state.players.find(x=>x.name===t);state.uses[p.name].power=true;let team=isHacker(target)?'HACKER':'BON';$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🔎 Résultat secret</h3><p><b>${esc(t)}</b> est dans le camp <b>${team}</b>.</p><button class="primary" id="analysisContinue">Continuer</button></div>`;bindVoice();$('analysisContinue').onclick=nightStep}}
function supportTurn(p){if(blocked(p.name)){state.nightStep++;return nightStep()}$('gameMessage').textContent='🤝 Le Support se réveille.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🤝 Support</h3><p>Tu peux utiliser ton pouvoir maintenant pour protéger un joueur cette nuit.</p><select id="supportTarget"><option value="">Choisir un joueur</option>${opts()}</select><button class="primary" id="supportConfirm">🤝 Protéger cette nuit</button><button class="secondary" id="supportSkip">Passer</button></div>`;bindVoice();speak('Le Support se réveille.');$('supportConfirm').onclick=()=>{let t=$('supportTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.supportProtected=t;state.uses[p.name].support=true;nightStep()};$('supportSkip').onclick=()=>nightStep()}
function wolfTurn(wolf,traitor){let actors=[wolf,traitor].filter(p=>p&&!blocked(p.name));if(!actors.length){nightStep();return}let actor=actors[0];$('gameMessage').textContent='🐺 Les Hackers se réveillent.';render(actors.map(p=>p.name));$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🐺 Décision des Hackers</h3><p>${actors.length>1?'Le Loup Gamer et le Traître choisissent une victime.':'Choisis secrètement la victime de cette nuit.'}</p><select id="nightTarget"><option value="">Choisir une victime</option>${opts(actor.name)}</select><button class="primary" id="wolfConfirm">🐺 Choisir la victime</button></div>`;bindVoice();speak('Les Hackers se réveillent.');$('wolfConfirm').onclick=()=>{let t=$('nightTarget').value;if(!t)return alert('⚠️ Choisis une victime.');state.nightVictim=t;nightStep()}}
function healTurn(p){if(blocked(p.name)){state.nightStep++;return nightStep()}$('gameMessage').textContent='❤️‍🩹 Le Healer se réveille.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>❤️‍🩹 Healer</h3><p>Choisis un joueur à protéger cette nuit.</p><select id="healTarget"><option value="">Choisir un joueur</option>${opts()}</select><button class="primary" id="healConfirm">❤️‍🩹 Protéger</button></div>`;bindVoice();speak('Le Healer se réveille.');$('healConfirm').onclick=()=>{let t=$('healTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.protected=t;finishNight()}}
function finishNight(){state.phase='day';let v=state.nightVictim,saved=v&&(v===state.protected||v===state.supportProtected);if(v&&!saved){let p=state.players.find(x=>x.name===v);if(p)p.alive=false}if(checkEnd())return;update('☀️ Jour');render();let text=saved?'❤️‍🩹 Une attaque a été empêchée cette nuit.':v?`☠️ ${v} a été éliminé pendant la nuit.`:'🌅 Personne n’a été éliminé cette nuit.';$('gameMessage').textContent=text;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>☀️ Le jour se lève</h3><p>${esc(text)}</p><button class="primary" id="dayBtn">☀️ Continuer</button></div>`;bindVoice();speak(text);$('dayBtn').onclick=startVote}
function startVote(){state.phase='vote';state.voteIndex=0;state.votes={};state.voteChanges=0;update('🗳️ Vote');let s=alive().find(p=>p.roleName==='Support'&&!state.uses[p.name].support);if(s){supportDay(s);return}showVote()}
function supportDay(p){$('gameMessage').textContent='🤝 Le Support peut encore agir.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🤝 Support</h3><p>Tu peux protéger un joueur contre l’élimination du vote.</p><select id="supportDayTarget"><option value="">Choisir un joueur</option>${opts()}</select><button class="primary" id="supportDayConfirm">🤝 Protéger pour le vote</button><button class="secondary" id="supportDaySkip">Passer</button></div>`;bindVoice();$('supportDayConfirm').onclick=()=>{let t=$('supportDayTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.supportProtected=t;state.uses[p.name].support=true;showVote()};$('supportDaySkip').onclick=showVote}
function showVote(){let a=alive();if(state.voteIndex>=a.length)return finishVote();let v=a[state.voteIndex];render([v.name]);$('gameMessage').textContent=`🗳️ ${v.name} doit voter.`;let choices=a.filter(p=>p.name!==v.name).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');let op=v.roleName==='Opportuniste';state.voteChanges=op?2:0;let double=v.roleName==='Speedrunner'&&!state.uses[v.name].double;$('actionArea').innerHTML=voice()+`<div class="night-card vote-card"><h3>🗳️ Tour de ${esc(v.name)}</h3><p>Choisis secrètement qui tu veux éliminer.</p>${double?'<p>⚡ Ton vote comptera double cette fois.</p>':''}<select id="voteTarget"><option value="">Choisir un joueur</option>${choices}</select><button class="primary" id="voteConfirm">🗳️ Valider mon vote</button></div>`;bindVoice();speak(`${v.name}, c'est à toi de voter.`);$('voteConfirm').onclick=()=>{let t=$('voteTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.votes[v.name]={target:t,weight:double?2:1};if(double)state.uses[v.name].double=true;if(op&&state.voteChanges>0){opportunisteChange(v);return}state.voteIndex++;showVote()}}
function opportunisteChange(v){state.voteChanges--;let choices=alive().filter(p=>p.name!==v.name).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');$('actionArea').innerHTML=voice()+`<div class="night-card vote-card"><h3>🎯 Opportuniste</h3><p>Vote actuel : <b>${esc(state.votes[v.name].target)}</b>. Tu peux encore changer ${state.voteChanges} fois.</p><select id="newVoteTarget"><option value="">Nouveau choix</option>${choices}</select><button class="primary" id="changeVoteBtn">🔄 Changer mon vote</button><button class="secondary" id="keepVoteBtn">✅ Garder ce vote</button></div>`;bindVoice();$('changeVoteBtn').onclick=()=>{let t=$('newVoteTarget').value;if(!t)return alert('⚠️ Choisis un nouveau vote.');state.votes[v.name].target=t;if(state.voteChanges>0)opportunisteChange(v);else{state.voteIndex++;showVote()}};$('keepVoteBtn').onclick=()=>{state.voteIndex++;showVote()}}
function finishVote(){let c={};Object.values(state.votes).forEach(x=>c[x.target]=(c[x.target]||0)+x.weight);let e=Object.entries(c).sort((a,b)=>b[1]-a[1]),el=null,msg='⚖️ Égalité : personne n’est éliminé.';if(e.length){let top=e[0],tie=e.filter(x=>x[1]===top[1]);if(tie.length===1){el=state.players.find(p=>p.name===top[0]);if(el&&(state.supportProtected===el.name)){msg=`🤝 ${el.name} est protégé : le vote ne l’élimine pas.`}else{let strat=alive().find(p=>p.roleName==='Stratège'&&!state.uses[p.name].strategy);if(strat){$('gameMessage').textContent=`🧠 Le Stratège peut annuler l'élimination de ${el.name}.`;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🧠 Stratège</h3><p>Une fois par partie, tu peux annuler cette élimination.</p><button class="primary" id="strategyYes">🧠 Annuler l’élimination</button><button class="secondary" id="strategyNo">Laisser faire</button></div>`;bindVoice();$('strategyYes').onclick=()=>{state.uses[strat.name].strategy=true;showVoteResult(`🧠 ${el.name} est sauvé par le Stratège.`);};$('strategyNo').onclick=()=>{el.alive=false;showVoteResult(`☠️ ${el.name} est éliminé avec ${top[1]} voix.`)};return}else{el.alive=false;msg=`☠️ ${el.name} est éliminé avec ${top[1]} voix.`}}}}if(checkEnd())return;showVoteResult(msg)}
function showVoteResult(msg){$('gameMessage').textContent=msg;$('aliveCount').textContent=alive().length;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>📊 Résultat du vote</h3><p>${esc(msg)}</p><button class="primary" id="nextRoundBtn">🌙 Commencer la nuit suivante</button></div>`;render([]);bindVoice();speak(msg);$('nextRoundBtn').onclick=startNextNight}
function startNextNight(){if(checkEnd())return;state.round++;state.phase='night';state.nightStep=0;state.nightVictim=null;state.protected=null;state.supportProtected=null;state.blocked=null;state.votes={};state.voteIndex=0;update(`🌙 Nuit ${state.round}`);render();nightIntro()}
$('startBtn').onclick=setup;$('minusPlayers').onclick=()=>changePlayers(-1);$('plusPlayers').onclick=()=>changePlayers(1);$('launchBtn').onclick=launch;$('showRoleBtn').onclick=reveal;$('nextRevealBtn').onclick=nextReveal;$('restartBtn').onclick=setup;document.querySelectorAll('.back').forEach(b=>b.onclick=()=>screen(b.dataset.screen));document.querySelectorAll('.special-role').forEach(x=>x.onchange=updateRoleCount);renderNames();
});