document.addEventListener('DOMContentLoaded',()=>{
const ROLES=[{name:'Joueur Gamer',icon:'🎮',team:'BONS',desc:'Aucun pouvoir. Gagne si tous les méchants sont éliminés.'},{name:'Loup Gamer',icon:'🐺',team:'HACKERS',desc:'Choisit secrètement une victime chaque nuit.'},{name:'Hacker',icon:'💻',team:'HACKERS',desc:'Un rôle Hacker sans pouvoir pour cette première base.'},{name:'Healer',icon:'❤️‍🩹',team:'BONS',desc:'Peut protéger un joueur pendant la nuit.'}];
let state={players:[],index:0,phase:'reveal',round:1,nightStep:0,nightVictim:null,protected:null,voteIndex:0,votes:{}},voiceEnabled=true,$=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')}
function speak(t){if(!voiceEnabled||!window.speechSynthesis)return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.88;u.pitch=.85;window.speechSynthesis.speak(u)}
function voice(){return `<button class="secondary" id="voiceBtn">🔊 Voix : ${voiceEnabled?'ON':'OFF'}</button>`}function bindVoice(){let b=$('voiceBtn');if(b)b.onclick=()=>{voiceEnabled=!voiceEnabled;if(!voiceEnabled&&window.speechSynthesis)window.speechSynthesis.cancel();b.textContent=`🔊 Voix : ${voiceEnabled?'ON':'OFF'}`}}
function renderNames(){let n=+$('playerCount').textContent||8,box=$('namesBox');box.innerHTML='';for(let i=1;i<=n;i++)box.insertAdjacentHTML('beforeend',`<div class="name-row"><label>👤 Joueur ${i}</label><input id="player-${i}" class="name-input" maxlength="20" placeholder="Entre ton pseudo" value="Joueur ${i}"></div>`)}
function setup(){renderNames();screen('setup')}function changePlayers(d){let e=$('playerCount');e.textContent=Math.max(5,Math.min(20,(+e.textContent||8)+d));renderNames()}
function launch(){let names=[...document.querySelectorAll('.name-input')].map(i=>i.value.trim());if(names.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');if(names.some(n=>!n))return alert('⚠️ Tous les joueurs doivent avoir un pseudo.');if(new Set(names.map(n=>n.toLowerCase())).size!==names.length)return alert('⚠️ Les pseudos doivent être différents.');let roles=names.map((_,i)=>i===0?ROLES[1]:i===1?ROLES[3]:i===2?ROLES[2]:ROLES[0]);for(let i=roles.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[roles[i],roles[j]]=[roles[j],roles[i]]}state={players:names.map((name,i)=>({name,role:roles[i],alive:true})),index:0,phase:'reveal',round:1,nightStep:0,nightVictim:null,protected:null,voteIndex:0,votes:{}};showReveal()}
function showReveal(){let p=state.players[state.index];if(!p)return;$('revealPlayer').textContent=p.name;$('roleCard').classList.add('hidden');$('showRoleBtn').classList.remove('hidden');screen('reveal')}
function reveal(){let p=state.players[state.index];if(!p)return;$('roleIcon').textContent=p.role.icon;$('roleName').textContent=p.role.name;$('roleTeam').textContent=p.role.team;$('roleDescription').textContent=p.role.desc;$('roleCard').classList.remove('hidden');$('showRoleBtn').classList.add('hidden');speak(`${p.name}, découvre ton rôle.`)}
function nextReveal(){if(++state.index>=state.players.length)startGame();else showReveal()}function alive(){return state.players.filter(p=>p.alive)}
function update(t){$('roundLabel').textContent=`TOUR ${state.round}`;$('phaseTitle').textContent=t;$('aliveCount').textContent=alive().length}
function render(active=[]){let a=new Set(active);$('playersList').innerHTML=state.players.map(p=>`<div class="player ${!p.alive?'dead':!a.size?'':a.has(p.name)?'active':'inactive'}"><strong>${esc(p.name)}</strong><br><small>${p.alive?'🟢 Vivant':'⚫ Éliminé'}</small></div>`).join('')}
function winner(){let a=alive(),h=a.filter(p=>p.role.team==='HACKERS').length,b=a.filter(p=>p.role.team==='BONS').length;if(h===0)return'BONS';if(h>=b)return'HACKERS';return null}
function checkEnd(){let w=winner();if(!w)return false;finish(w);return true}
function finish(w){state.phase='end';let h=w==='HACKERS',msg=h?'Les Hackers sont désormais aussi nombreux que les Bons. Ils remportent la partie !':'Tous les Hackers ont été éliminés. Le village remporte la partie !';$('winnerIcon').textContent=h?'🐺':'🛡️';$('winnerTitle').textContent=h?'Victoire des HACKERS !':'Victoire des BONS !';$('winnerMessage').textContent=msg;$('finalPlayers').innerHTML=state.players.map(p=>`<div class="final-player ${p.alive?'':'dead'}"><strong>${p.alive?'🟢':'⚫'} ${esc(p.name)}</strong><span><b>${p.role.icon} ${esc(p.role.name)}</b><br><small>${esc(p.role.team)}</small></span></div>`).join('');screen('end');speak(msg)}
function startGame(){state.phase='night';state.round=1;state.nightStep=0;state.nightVictim=null;state.protected=null;state.votes={};screen('game');update('🌙 Nuit 1');render();nightIntro()}
function nightIntro(){if(checkEnd())return;$('gameMessage').textContent=`La nuit ${state.round} commence.`;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🌙 La nuit tombe...</h3><p>Tout le village s'endort. Les rôles qui ont une action vont maintenant jouer.</p><button class="primary" id="startNightBtn">🌙 Commencer la nuit</button></div>`;bindVoice();speak('La nuit tombe sur le village. Tout le monde ferme les yeux.');$('startNightBtn').onclick=nightStep}
function opts(exclude=''){return alive().filter(p=>p.name!==exclude).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('')}
function nightStep(){let w=alive().find(p=>p.role.name==='Loup Gamer'),h=alive().find(p=>p.role.name==='Healer');if(state.nightStep===0&&w){state.nightStep=1;wolfTurn(w);return}if(state.nightStep<=1&&h){state.nightStep=2;healTurn(h);return}finishNight()}
function wolfTurn(p){$('gameMessage').textContent='🐺 Les Loups se réveillent.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>🐺 Loup Gamer</h3><p>Choisis secrètement la victime de cette nuit.</p><select id="nightTarget"><option value="">Choisir une victime</option>${opts(p.name)}</select><button class="primary" id="wolfConfirm">🐺 Choisir la victime</button></div>`;bindVoice();speak('Les Loups se réveillent. Choisis secrètement une victime.');$('wolfConfirm').onclick=()=>{let t=$('nightTarget').value;if(!t)return alert('⚠️ Choisis une victime.');state.nightVictim=t;nightStep()}}
function healTurn(p){$('gameMessage').textContent='❤️‍🩹 Le Healer se réveille.';render([p.name]);$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>❤️‍🩹 Healer</h3><p>Choisis un joueur à protéger cette nuit.</p><select id="healTarget"><option value="">Choisir un joueur</option>${opts()}</select><button class="primary" id="healConfirm">❤️‍🩹 Protéger</button></div>`;bindVoice();speak('Le Healer se réveille. Choisis un joueur à protéger.');$('healConfirm').onclick=()=>{let t=$('healTarget').value;if(!t)return alert('⚠️ Choisis un joueur à protéger.');state.protected=t;finishNight()}}
function finishNight(){state.phase='day';let v=state.nightVictim,saved=v&&v===state.protected;if(v&&!saved){let p=state.players.find(x=>x.name===v);if(p)p.alive=false}if(checkEnd())return;update('☀️ Jour');render();let text=saved?'❤️‍🩹 Une attaque a été empêchée cette nuit.':v?`☠️ ${v} a été éliminé pendant la nuit.`:'🌅 Personne n’a été éliminé cette nuit.';$('gameMessage').textContent=text;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>☀️ Le jour se lève</h3><p>${esc(text)}</p><button class="primary" id="dayBtn">☀️ Continuer</button></div>`;bindVoice();speak(text);$('dayBtn').onclick=startVote}
function startVote(){state.phase='vote';state.voteIndex=0;state.votes={};update('🗳️ Vote');$('gameMessage').textContent='Le village doit choisir un joueur à éliminer.';showVote()}
function showVote(){let a=alive();if(state.voteIndex>=a.length)return finishVote();let v=a[state.voteIndex];render([v.name]);$('gameMessage').textContent=`🗳️ ${v.name} doit voter.`;let choices=a.filter(p=>p.name!==v.name).map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');$('actionArea').innerHTML=voice()+`<div class="night-card vote-card"><h3>🗳️ Tour de ${esc(v.name)}</h3><p>Choisis secrètement qui tu veux éliminer.</p><select id="voteTarget"><option value="">Choisir un joueur</option>${choices}</select><button class="primary" id="voteConfirm">🗳️ Valider mon vote</button></div>`;bindVoice();speak(`${v.name}, c'est à toi de voter.`);$('voteConfirm').onclick=()=>{let t=$('voteTarget').value;if(!t)return alert('⚠️ Choisis un joueur.');state.votes[v.name]=t;state.voteIndex++;showVote()}}
function finishVote(){let c={};Object.values(state.votes).forEach(t=>c[t]=(c[t]||0)+1);let e=Object.entries(c).sort((a,b)=>b[1]-a[1]),el=null,msg='⚖️ Égalité : personne n’est éliminé.';if(e.length){let top=e[0],tie=e.filter(x=>x[1]===top[1]);if(tie.length===1){el=state.players.find(p=>p.name===top[0]);if(el)el.alive=false;msg=`☠️ ${top[0]} est éliminé avec ${top[1]} vote${top[1]>1?'s':''}.`}}if(el&&checkEnd())return;$('gameMessage').textContent=msg;$('aliveCount').textContent=alive().length;$('actionArea').innerHTML=voice()+`<div class="night-card"><h3>📊 Résultat du vote</h3>${e.map(([n,v])=>`<div class="vote-result"><strong>${esc(n)}</strong><span>${v} vote${v>1?'s':''}</span></div>`).join('')}<p>${esc(msg)}</p><button class="primary" id="nextRoundBtn">🌙 Commencer la nuit suivante</button></div>`;render([]);bindVoice();speak(msg);$('nextRoundBtn').onclick=startNextNight}
function startNextNight(){if(checkEnd())return;state.round++;state.phase='night';state.nightStep=0;state.nightVictim=null;state.protected=null;state.votes={};state.voteIndex=0;update(`🌙 Nuit ${state.round}`);render();nightIntro()}
$('startBtn').onclick=setup;$('minusPlayers').onclick=()=>changePlayers(-1);$('plusPlayers').onclick=()=>changePlayers(1);$('launchBtn').onclick=launch;$('showRoleBtn').onclick=reveal;$('nextRevealBtn').onclick=nextReveal;$('restartBtn').onclick=setup;document.querySelectorAll('.back').forEach(b=>b.onclick=()=>screen(b.dataset.screen));renderNames();
});