document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),SUPABASE_URL='https://qhakagliayozwviqkklw.supabase.co',SUPABASE_KEY='sb_publishable_YPMhL1PcQrZO8e6a_Py8kQ_sB57lKyO',sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const ROLES={
'Joueur Gamer':['🎮','BONS','Aucun pouvoir.'],'Loup Gamer':['🐺','HACKERS','Choisit une victime chaque nuit.'],'Healer':['❤️‍🩹','BONS','Protège un joueur chaque nuit.'],'Stratège':['🧠','BONS','Peut annuler une élimination par vote.'],'Support':['🤝','BONS','Protège une fois.'],'Analyste':['🔎','BONS','Découvre secrètement un camp.'],'Speedrunner':['⚡','BONS','Peut utiliser un vote double une fois.'],'Hacker':['💻','HACKERS','Bloque un pouvoir une fois.'],'Saboteur':['🧨','HACKERS','Déclenche un faux événement une fois.'],'Manipulateur':['🎭','SOLO','Gagne lorsqu’il reste 3 joueurs.'],'Chaos':['🌀','SOLO','Gagne si ses 2 cibles secrètes meurent.'],'Opportuniste':['🎯','SOLO','Peut changer son vote 2 fois et gagne avec le camp victorieux.'],'Boss Final':['👑','SOLO','Gagne s’il est le dernier vivant.'],'Traître':['🗡️','BONS','Rejoint les HACKERS au tour 3.']};
let n={host:false,room:'',roomId:null,pseudo:'',playerId:crypto.randomUUID(),channel:null,players:[],settings:{max:8,roles:[]},game:null};
const screen=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active')};
const status=t=>[$('onlineStatus'),$('joinStatus')].forEach(e=>{if(e)e.textContent=t});
const alive=()=>n.players.filter(p=>p.alive);
const me=()=>n.players.find(p=>p.playerId===n.playerId);
const hacker=p=>p.roleName==='Loup Gamer'||p.roleName==='Hacker'||p.roleName==='Saboteur'||(p.roleName==='Traître'&&(n.game?.round||1)>=3);
const code=()=> 'L64-'+Math.random().toString(36).slice(2,8).toUpperCase();
function lobby(){if($('lobbyOptionsBtn'))$('lobbyOptionsBtn').style.display=n.host?'block':'none';if($('startOnlineGameBtn'))$('startOnlineGameBtn').style.display=n.host?'block':'none';if($('leaveOnlineBtn'))$('leaveOnlineBtn').style.display=n.host?'none':'block';if($('roomCodeDisplay'))$('roomCodeDisplay').textContent=n.room;if($('lobbyPlayers'))$('lobbyPlayers').innerHTML=n.players.map((p,i)=>'<div class="player '+(i===0?'active':'')+'"><strong>'+esc(p.pseudo)+'</strong><span>'+(i===0?'👑 Hôte':'🟢 Joueur')+'</span></div>').join('');if($('startOnlineGameBtn'))$('startOnlineGameBtn').disabled=!n.host||n.players.length<5}
async function load(){if(!n.roomId)return;const r=await sb.from('game_players').select('*').eq('room_id',n.roomId).order('joined_at');if(r.error)return status('❌ '+r.error.message);n.players=r.data.map(p=>({id:p.id,playerId:p.player_id,pseudo:p.pseudo,alive:p.alive,roleName:p.role_data?.roleName||null,role:p.role_data?.role||null,uses:p.role_data?.uses||{},targets:p.role_data?.targets||[]}));lobby();if(n.game)renderGame()}
function sub(){if(n.channel)sb.removeChannel(n.channel);n.channel=sb.channel('room-'+n.roomId).on('postgres_changes',{event:'*',schema:'public',table:'game_players',filter:'room_id=eq.'+n.roomId},load).on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_rooms',filter:'id=eq.'+n.roomId},p=>{n.game=p.new.state?.game||null;if(p.new.phase==='game'&&n.game){renderGame();if(n.host)hostTick(n.game)}}).subscribe()}
async function roomUpdate(game){n.game=game;await sb.from('game_rooms').update({phase:'game',state:{settings:n.settings,game},updated_at:new Date().toISOString()}).eq('id',n.roomId)}
async function create(){const pseudo=$('createPseudo').value.trim();if(!pseudo)return alert('⚠️ Entre ton pseudo.');n.host=true;n.pseudo=pseudo;n.room=code();n.settings={max:+($('onlinePlayerCount')?.textContent||8),roles:[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value)};status('Création du salon…');const r=await sb.from('game_rooms').insert({code:n.room,host_id:n.playerId,phase:'lobby',state:{settings:n.settings}}).select().single();if(r.error)return status('❌ '+r.error.message);n.roomId=r.data.id;const e=await sb.from('game_players').insert({room_id:r.data.id,player_id:n.playerId,pseudo,is_host:true});if(e.error)return status('❌ '+e.error.message);sub();await load();screen('onlineLobby');status('🟢 Salon créé : '+n.room)}
async function join(){const pseudo=$('joinPseudo').value.trim(),c=$('roomCode').value.trim().replace(/\s+/g,'').toUpperCase();if(!pseudo||!c)return alert('⚠️ Pseudo + code requis.');status('🔎 Recherche du salon…');const r=await sb.from('game_rooms').select('*').eq('code',c).maybeSingle();if(!r.data)return status('❌ Salon introuvable.');if(r.data.phase!=='lobby')return status('❌ Partie déjà commencée.');const count=await sb.from('game_players').select('*',{count:'exact',head:true}).eq('room_id',r.data.id);if((count.count||0)>=(r.data.state?.settings?.max||8))return status('❌ Salon complet.');const e=await sb.from('game_players').insert({room_id:r.data.id,player_id:n.playerId,pseudo,is_host:false});if(e.error)return status('❌ '+e.error.message);n.host=false;n.pseudo=pseudo;n.roomId=r.data.id;n.room=r.data.code;n.settings=r.data.state?.settings||{max:8,roles:[]};sub();await load();screen('onlineLobby');status('🟢 Connecté au salon.')}
async function save(){if(!n.host)return;n.settings.max=+$('onlinePlayerCount').textContent;n.settings.roles=[...document.querySelectorAll('.online-special-role:checked')].map(x=>x.value);await sb.from('game_rooms').update({state:{settings:n.settings},updated_at:new Date().toISOString()}).eq('id',n.roomId);lobby();screen('onlineLobby')}
function chooseRoles(){let pool=['Loup Gamer','Healer',...n.settings.roles.filter(x=>ROLES[x]&&x!=='Joueur Gamer')];while(pool.length<n.players.length)pool.push('Joueur Gamer');return pool.slice(0,n.players.length).sort(()=>Math.random()-.5)}
async function start(){if(!n.host||n.players.length<5)return alert('⚠️ Il faut au moins 5 joueurs.');let roles=chooseRoles();for(let i=0;i<n.players.length;i++){let targets=[];if(roles[i]==='Chaos')targets=n.players.filter((_,j)=>j!==i).sort(()=>Math.random()-.5).slice(0,2).map(p=>p.playerId);await sb.from('game_players').update({alive:true,role_data:{roleName:roles[i],role:ROLES[roles[i]],uses:{},targets}}).eq('id',n.players[i].id)}await load();const game={round:1,phase:'reveal',ready:{},night:{queue:[],index:0,actions:{},blocked:[]},vote:{votes:{},changes:{}},message:'Découvrez vos rôles.'};await roomUpdate(game);renderGame()}
function roleCard(p){const r=ROLES[p.roleName];const cardMap={'Traître':'01','Manipulateur':'02','Chaos':'02','Opportuniste':'02','Boss Final':'02','Saboteur':'03','Analyste':'04','Healer':'05','Loup Gamer':'06','Hacker':'07','Support':'08','Speedrunner':'09','Stratège':'10','Joueur Gamer':'11'};const card='cartes/carte_'+(cardMap[p.roleName]||'11')+'.png';const back='cartes/dos.png';return '<div class="role-reveal"><div class="role-card-visual"><div class="card-flip"><div class="card-face card-front" style="background-image:url(&quot;'+back+'&quot;)"></div><div class="card-face card-back" style="background-image:url(&quot;'+card+'&quot;)"><div class="card-role-badge">'+r[0]+'<span>'+esc(p.roleName)+'</span></div></div></div></div><div class="night-card role-info"><h3>🎭 Ta carte</h3><div class="role-icon">'+r[0]+'</div><h3>'+esc(p.roleName)+'</h3><p>'+esc(r[2])+'</p><button class="primary" id="onlineReady">Continuer</button></div></div>'}function renderGame(){screen('onlineGame');const p=me(),g=n.game||{};$('onlineRound').textContent='TOUR '+(g.round||1);$('onlinePhase').textContent=g.phase==='reveal'?'🎭 Rôles':g.phase==='night'?'🌙 Nuit':g.phase==='vote'?'🗳️ Vote':g.phase==='end'?'🏆 Fin':'☀️ Jour';$('onlineAlive').textContent=alive().length;$('onlinePlayers').innerHTML=n.players.map(x=>'<div class="player '+(x.alive?'active':'dead')+'"><strong>'+esc(x.pseudo)+'</strong><small>'+(x.alive?'🟢 Vivant':'⚫ Éliminé')+'</small></div>').join('');if(g.phase==='reveal'){if(!p)return; $('onlineAction').innerHTML=roleCard(p);$('onlineReady').onclick=()=>readyReveal()}else if(g.phase==='night')renderNight(p);else if(g.phase==='vote')renderVote(p);else if(g.phase==='day')renderDay(p);else renderEnd()}
async function setGame(game){await roomUpdate(game);if(n.host)await hostTick(game)}
async function readyReveal(){let g=JSON.parse(JSON.stringify(n.game));g.ready[n.playerId]=true;await setGame(g)}
function nightQueue(g){let q=[];const addRole=r=>{const p=alive().find(x=>x.roleName===r);if(p&&!p.uses?.used)return q.push({id:p.playerId,type:r})};addRole('Hacker');addRole('Saboteur');addRole('Analyste');addRole('Support');let wolves=alive().filter(x=>x.roleName==='Loup Gamer'||(x.roleName==='Traître'&&g.round>=3));wolves.forEach(p=>q.push({id:p.playerId,type:'wolf'}));addRole('Healer');return q}
async function startNight(g){g.phase='night';g.night={queue:nightQueue(g),index:0,actions:{},blocked:[]};g.message='🌙 La nuit tombe…';await setGame(g)}
function actor(){const a=n.game?.night?.queue?.[n.game.night.index];return a?n.players.find(p=>p.playerId===a.id):null}
function renderNight(p){const a=actor();if(!a){$('onlineAction').innerHTML='<div class="night-card"><h3>🌙 Nuit</h3><p>Le maître du jeu prépare la suite…</p></div>';return}if(p?.playerId!==a.playerId){$('onlineAction').innerHTML='<div class="night-card"><h3>🌙 Nuit</h3><p>Un autre joueur agit. Attends ton tour…</p></div>';return}const type=n.game.night.queue[n.game.night.index].type;if(p.uses?.[type==='wolf'?'wolf':type]){if(n.host)hostTick(n.game);return}let targets=alive().filter(x=>type==='Support'||type==='wolf'?true:x.playerId!==p.playerId);let opts=targets.map(x=>'<option value="'+x.playerId+'">'+esc(x.pseudo)+'</option>').join('');let title={Hacker:'💻 Hacker',Saboteur:'🧨 Saboteur',Analyste:'🔎 Analyste',Support:'🤝 Support',wolf:'🐺 Choisis une victime',Healer:'❤️‍🩹 Healer'}[type]||type;if(type==='Saboteur'){$('onlineAction').innerHTML='<div class="night-card"><h3>🧨 Saboteur</h3><p>Déclencher le faux événement ?</p><button class="primary" id="sabotageConfirm">🧨 Saboter</button></div>';$('sabotageConfirm').onclick=()=>submitNightAction(p,'Saboteur','1');return} $('onlineAction').innerHTML='<div class="night-card"><h3>'+title+'</h3><p>Choisis une cible.</p><select id="nightTarget"><option value="">Choisir</option>'+opts+'</select><button class="primary" id="nightConfirm">Valider</button></div>';$('nightConfirm').onclick=()=>{let t=$('nightTarget').value;if(!t)return alert('⚠️ Choisis une cible.');submitNightAction(p,type,t)}}
async function submitNightAction(p,type,target){let g=JSON.parse(JSON.stringify(n.game));g.night.actions[p.playerId]={type,target};if(type==='Hacker')g.night.blocked.push(target);g.night.index++;await setGame(g)}
async function hostTick(g){if(!n.host||g.phase!=='night')return;let q=g.night.queue;if(g.night.index<q.length){const a=q[g.night.index],p=n.players.find(x=>x.playerId===a.id);if(p&&p.uses?.[a.type==='wolf'?'wolf':a.type]){g.night.index++;await roomUpdate(g);return}return}let victim=null,prot=null;Object.values(g.night.actions).forEach(a=>{if(a.type==='wolf')victim=a.target;if(a.type==='Healer'||a.type==='Support')prot=a.target});if(victim&&victim!==prot){const v=n.players.find(x=>x.playerId===victim);if(v){await sb.from('game_players').update({alive:false}).eq('id',v.id);v.alive=false;g.message='☠️ '+v.pseudo+' a été éliminé pendant la nuit.'}}else g.message='🌙 Personne n’a été éliminé cette nuit.';await load();const w=winner();if(w){await finish(w,g);return}g.phase='day';await roomUpdate(g);setTimeout(()=>{if(n.host)startVote(g)},800)}
async function startVote(g){g.phase='vote';g.vote={votes:{},changes:{}};g.message='🗳️ Tous les joueurs vivants votent.';await roomUpdate(g)}
function renderVote(p){if(!p?.alive){$('onlineAction').innerHTML='<div class="night-card"><h3>👻 Tu es éliminé</h3><p>Observe la partie.</p></div>';return}const voted=n.game.vote?.votes?.[p.playerId];const canChange=p.roleName==='Opportuniste'&&(n.game.vote.changes?.[p.playerId]||0)<2;let choices=alive().filter(x=>x.playerId!==p.playerId).map(x=>'<option value="'+x.playerId+'">'+esc(x.pseudo)+'</option>').join('');$('onlineAction').innerHTML='<div class="night-card"><h3>🗳️ Vote secret</h3><p>'+(voted?'Vote actuel : <b>'+esc(n.players.find(x=>x.playerId===voted.target)?.pseudo||'')+'</b>':'Choisis qui éliminer.')+'</p><select id="voteTarget"><option value="">Choisir</option>'+choices+'</select><label style="display:block;margin:10px 0"><input id="doubleVote" type="checkbox" '+(p.roleName==='Speedrunner'&&!p.uses?.double?'':'disabled')+'> ⚡ Utiliser mon vote double</label><button class="primary" id="voteConfirm">'+(voted?'🔄 Modifier le vote':'🗳️ Voter')+'</button>'+(canChange&&voted?'<button class="secondary" id="keepVote">Garder ce vote</button>':'')+'</div>';$('voteConfirm').onclick=()=>{let t=$('voteTarget').value;if(!t)return alert('⚠️ Choisis une cible.');submitVote(p,t,$('doubleVote').checked)};if($('keepVote'))$('keepVote').onclick=()=>{}}
async function submitVote(p,target,double){let g=JSON.parse(JSON.stringify(n.game));g.vote.votes[p.playerId]={target,weight:double?2:1};if(double){await sb.from('game_players').update({role_data:{roleName:p.roleName,role:ROLES[p.roleName],uses:{...(p.uses||{}),double:true},targets:p.targets||[]}}).eq('id',p.id)}if(p.roleName==='Opportuniste')g.vote.changes[p.playerId]=(g.vote.changes[p.playerId]||0)+1;await setGame(g)}
async function resolveVote(g){let c={};Object.values(g.vote.votes).forEach(v=>c[v.target]=(c[v.target]||0)+v.weight);let e=Object.entries(c).sort((a,b)=>b[1]-a[1]);if(!e.length)return startNight({...g,round:g.round+1});let top=e[0],tie=e.filter(x=>x[1]===top[1]);if(tie.length>1){g.message='⚖️ Égalité : personne n’est éliminé.';g.phase='day';await roomUpdate(g);setTimeout(()=>{if(n.host)startNight({...g,round:g.round+1})},1200);return}let target=n.players.find(p=>p.playerId===top[0]);let strat=alive().find(p=>p.roleName==='Stratège'&&!p.uses?.strategy);if(strat){g.phase='day';g.vote.pending={target:target.playerId,score:top[1],strat:strat.playerId};g.message='🧠 Le Stratège peut annuler l’élimination.';await roomUpdate(g);return}await eliminateVote(target,g,top[1])}
async function eliminateVote(target,g,score){if(!target)return;await sb.from('game_players').update({alive:false}).eq('id',target.id);target.alive=false;g.message='☠️ '+target.pseudo+' est éliminé avec '+score+' voix.';await load();const w=winner();if(w){await finish(w,g);return}g.phase='day';await roomUpdate(g);setTimeout(()=>{if(n.host)startNight({...g,round:g.round+1})},1400)}
function renderDay(p){if(n.game.vote?.pending&&p?.playerId===n.game.vote.pending.strat){$('onlineAction').innerHTML='<div class="night-card"><h3>🧠 Stratège</h3><p>Annuler l’élimination de '+esc(n.players.find(x=>x.playerId===n.game.vote.pending.target)?.pseudo||'')+' ?</p><button class="primary" id="stratYes">🧠 Annuler</button><button class="secondary" id="stratNo">Laisser faire</button></div>';$('stratYes').onclick=()=>stratAction(true);$('stratNo').onclick=()=>stratAction(false)}else $('onlineAction').innerHTML='<div class="night-card"><h3>☀️ Jour</h3><p>'+esc(n.game.message||'La journée commence.')+'</p></div>'}
async function stratAction(cancel){if(!n.host&&n.game.vote.pending.strat!==n.playerId)return;let g=JSON.parse(JSON.stringify(n.game)),t=n.players.find(p=>p.playerId===g.vote.pending.target),s=n.players.find(p=>p.playerId===g.vote.pending.strat);await sb.from('game_players').update({role_data:{roleName:s.roleName,role:ROLES[s.roleName],uses:{...(s.uses||{}),strategy:true},targets:s.targets||[]}}).eq('id',s.id);delete g.vote.pending;if(cancel){g.message='🧠 Le Stratège a annulé l’élimination.';g.phase='day';await roomUpdate(g);setTimeout(()=>{if(n.host)startNight({...g,round:g.round+1})},1400)}else eliminateVote(t,g,1)}
function winner(){let a=alive();let m=a.find(p=>p.roleName==='Manipulateur');if(m&&a.length<=3)return'MANIPULATEUR';let c=a.find(p=>p.roleName==='Chaos');if(c&&c.targets?.length===2&&c.targets.every(id=>!n.players.find(p=>p.playerId===id)?.alive))return'CHAOS';let b=a.find(p=>p.roleName==='Boss Final');if(b&&a.length===1)return'BOSS FINAL';let h=a.filter(hacker).length,bons=a.filter(p=>!hacker(p)&&!['Manipulateur','Chaos','Boss Final'].includes(p.roleName)).length;if(h===0)return'BONS';if(h>=bons)return'HACKERS';return null}
async function finish(w,g){g.phase='end';g.winner=w;g.message='🏆 Victoire : '+w;g.finalPlayers=n.players.map(p=>({pseudo:p.pseudo,alive:p.alive,role:p.roleName}));await roomUpdate(g)}
function renderEnd(){const g=n.game;$('onlineAction').innerHTML='<div class="night-card"><h3>🏆 '+esc(g.winner)+'</h3><p>'+esc(g.message||'Fin de partie.')+'</p></div>';$('onlinePlayers').innerHTML=(g.finalPlayers||[]).map(p=>'<div class="player '+(p.alive?'active':'dead')+'"><strong>'+esc(p.pseudo)+'</strong><small>'+esc(p.role||'')+(p.alive?' 🟢':' ⚫')+'</small></div>').join('')}
async function hostTick(g){if(!n.host)return;if(g.phase==='reveal'){if(Object.keys(g.ready||{}).length>=n.players.length)await startNight(g);return}if(g.phase==='night'){let q=g.night.queue;if(g.night.index>=q.length){let victim=null,prot=null;Object.values(g.night.actions).forEach(a=>{if(a.type==='wolf')victim=a.target;if(a.type==='Healer'||a.type==='Support')prot=a.target});if(victim&&victim!==prot){let v=n.players.find(p=>p.playerId===victim);if(v){await sb.from('game_players').update({alive:false}).eq('id',v.id);v.alive=false;g.message='☠️ '+v.pseudo+' a été éliminé pendant la nuit.'}}else g.message='🌙 Personne n’a été éliminé cette nuit.';await load();let w=winner();if(w){await finish(w,g);return}g.phase='day';await roomUpdate(g);setTimeout(()=>{if(n.host)startVote(g)},1000)}}else if(g.phase==='vote'&&Object.keys(g.vote.votes||{}).length>=alive().length)await resolveVote(g)}
$('leaveOnlineBtn')?.addEventListener('click',async()=>{if(!n.roomId)return;const ok=confirm('Quitter ce salon ?');if(!ok)return;await sb.from('game_players').delete().eq('room_id',n.roomId).eq('player_id',n.playerId);if(n.channel)await sb.removeChannel(n.channel);n.roomId=null;n.room='';n.players=[];n.game=null;screen('online');status('');});$('onlineBtn')?.addEventListener('click',()=>screen('online'));$('createOnlineBtn')?.addEventListener('click',()=>screen('onlineCreate'));$('joinOnlineBtn')?.addEventListener('click',()=>screen('onlineJoin'));$('createRoomBtn')?.addEventListener('click',create);$('joinRoomBtn')?.addEventListener('click',join);$('saveOnlineOptionsBtn')?.addEventListener('click',save);$('startOnlineGameBtn')?.addEventListener('click',start);$('lobbyOptionsBtn')?.addEventListener('click',()=>screen('onlineOptions'));$('onlineMinusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.max(5,+e.textContent-1)});$('onlinePlusPlayers')?.addEventListener('click',()=>{const e=$('onlinePlayerCount');e.textContent=Math.min(20,+e.textContent+1)});document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>screen(b.dataset.screen||'home')));
});